src/com/base/game/character/npc/NPC.java, src/com/base/game/character/npc/dominion/Brax.java, src/com/base/game/character/npc/dominion/HarpyBimbo.java, src/com/base/game/character/npc/dominion/HarpyNympho.java, src/com/base/game/character/race/Race.java, src/com/base/game/dialogue/DialogueFlags.java, src/com/base/game/dialogue/places/dominion/EnforcerHQDialogue.java, src/com/base/game/dialogue/places/dominion/harpyNests/HarpyNestBimbo.java, src/com/base/game/dialogue/places/dominion/harpyNests/HarpyNestDominant.java, src/com/base/game/dialogue/places/dominion/harpyNests/HarpyNestNympho.java, src/com/base/game/inventory/clothing/ClothingType.java, src/com/base/game/sex/sexActions/dominion/brax/SABraxSubCowgirl.java, src/com/base/utils/Util.java
These are the typos and other small changes I did. Hope all's well with them. Merge as you see fit.
=> Typos and other changes

src/com/base/game/sex/managers/universal/SMDomSelfKneeling.java, src/com/base/game/sex/sexActions/baseActionsMisc/GenericPositioning.java
Added SMDomSelfKneeling class
Added PLAYER_FORCE_POSITION_SELF_KNEELING to GenericPositioning.java
Very simple addition. Unsure if descriptions in GenericPositioning.java are adequate.
=> Added the ability to kneel when you're the dom

src/com/base/game/dialogue/utils/InventoryDialogue.java
Added InventorySlotsTaken check to each loop within Take all's effects
=> Fixed hang on inventory when taking all

src/com/base/game/character/GameCharacter.java
=> Fix for Horse Hair

src/com/base/game/character/GameCharacter.java
=> Fixing Feline leg covering

src/com/base/game/dialogue/utils/InventoryDialogue.java, src/com/base/game/sex/SexPosition.java, src/com/base/game/sex/managers/universal/SMDomSelfDoggy.java, src/com/base/game/sex/sexActions/baseActionsMisc/GenericPositioning.java
Just a quick set of changes to allow players to go into self-doggy style and to ride cocks anally while being dominant.
=> Adding dom self-penetration moves

src/com/base/game/dialogue/utils/InventoryDialogue.java
also added a check for whether you have enough inventory space to dye an item
=> fix bug where dyeing stacked clothes would dye the entire stack

src/com/base/game/dialogue/utils/PhoneDialogue.java, src/com/base/res/css/webView_stylesheet.css, src/com/base/res/css/webView_stylesheet_light.css
Effects column did get a few pixels smaller =/ but at least it doesn't leave huge gaps now
=> Fix long item description in encyclopedia from leaving gaps

src/com/base/game/dialogue/utils/InventoryDialogue.java, src/com/base/game/dialogue/utils/OptionsDialogue.java
This probably needs review and testing
The testing itself is probably a good time to document all the bugs in the shop menu.
=> Cleanup inventory dialogue + fix required java version to be 1.8.0_131, not 0.1.8.0_131

src/com/base/game/character/CharacterUtils.java, src/com/base/main/Main.java
tail fix antennae fix, anus fix, penis modifiers fixes, I dunno I just fixed crap until the console was fine
=> FIX EVERYTHING

src/com/base/game/combat/Combat.java, src/com/base/main/Main.java, src/com/base/world/World.java
=> sonarlint; reorder modifiers to comply with java language specification

src/com/base/main/Main.java, src/com/base/utils/Util.java
- Removed Util.getFileExtention, replaced by a FilenameFilter
- Fleshed out / fixed up some Javadocs
- Did some witchcraftery on the stringList functions :)
=> Cleanup Util

src/com/base/game/Game.java, src/com/base/game/character/body/Body.java, src/com/base/game/dialogue/DialogueNodeOld.java, src/com/base/game/dialogue/places/dominion/lilayashome/Library.java, src/com/base/game/dialogue/places/dominion/shoppingArcade/SuccubisSecrets.java, src/com/base/game/dialogue/utils/CharacterModificationUtils.java, src/com/base/game/sex/sexActions/baseActionsPartner/PartnerFingerNipple.java
running list of bugs I find in the preview version, mergable when you feel like releasing the preview
=> Preview fixes

src/com/lilithsthrone/game/dialogue/utils/EnchantmentDialogue.java, src/com/lilithsthrone/utils/Util.java
Not a big contribution, but it's something.
When a number between 0 and 20 (inclusive) is input, the new code completes in 1/3 to 1/2 of the old code's time.
When a number greater than 20 is input, the new code completes in similar time as the old code.
The new code's class file is 103 bytes smaller than the old code's file.
=> Util.intToString optimization and removal of EnchantmentDialogue.getRarityIdentifier

src/com/lilithsthrone/main/Main.java
Made use of try-with-resources to ensure the everything is closed even if loading fails.
=> Fixed #72 and made sure everything is closed properly

src/com/lilithsthrone/game/inventory/clothing/ClothingType.java
Fan requested black lab coats, for their evil days. They shall be submitting a child for the processing fee.
=> Update Lab coats, for the evil scientist.

src/com/lilithsthrone/game/dialogue/places/dominion/CityPlaces.java, src/com/lilithsthrone/utils/Util.java
There was a check in the intToString that checked if the number was
Bigger than 0, yet for the "times" bug, you'd need the zero to be done
as well.
Also on line 357 there was getLostPlayerCount instead of
getFoughtPlayerCount
=> Removed an "unneeded" check (domionion dialogue bugfix)

src/com/lilithsthrone/game/inventory/item/ItemEffectType.java
This adds throat capacity, elasticity, plasticity and wetness as usable enchantments when modifying the mouth.
Relates to #136 (blowjob skill is unaffected by this PR)
=> Added enchantments for throats.

src/com/lilithsthrone/game/inventory/item/ItemEffectType.java
=> Fix incorrect inequalities for set to limit check

src/com/lilithsthrone/game/dialogue/utils/OptionsDialogue.java
testing Desktop.isDesktopSupported() or
Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)
did not work on my platform. So just resorted to the other way around
approach.
Signed-off-by: picobyte <PiC.o0.o.BytE@gmail.com>
=> fix opening an url

src/com/lilithsthrone/game/character/body/Body.java, src/com/lilithsthrone/game/dialogue/places/dominion/lilayashome/Lab.java, src/com/lilithsthrone/game/dialogue/places/dominion/zaranixHome/ZaranixHomeFirstFloor.java, src/com/lilithsthrone/game/dialogue/places/dominion/zaranixHome/ZaranixHomeGroundFloor.java
I hope I'm doing this right, it at least looks like it. Takes a while to get into Github.
Not much to say. The second "kimonos" is maybe debatable though, and I hope getNameSingular is really the correct way to get the singular name.
=> Couple typo fixes

src/com/lilithsthrone/rendering/RenderingEngine.java
Now the cum splatter is shown even when not equipped. Did some testing, seems to work
Signed-off-by: picobyte <PiC.o0.o.BytE@gmail.com>
=> Fix issue Dirty clothing icon missing in inventory #128

src/com/lilithsthrone/game/sex/sexActions/baseActionsPartner/PartnerPenisAnus.java
This is just a simple fix for the PC teasing an NPC's cock with their anus.
=> Fix for incorrect lubrication on PC anal tease

src/com/lilithsthrone/game/sex/sexActions/baseActionsPlayer/PlayerFingerNipple.java, src/com/lilithsthrone/game/sex/sexActions/baseActionsSelfPlayer/PlayerSelfFingerNipple.java
Arguably, you should be able to grope someone's chest too even if they're completely flat, but I think that would require some rewriting of the descriptions. This was a purely mechanical change, which I'm more comfortable with.
=> Remove requirement for characters to have breasts to pinch nipples

src/com/lilithsthrone/game/character/body/Body.java
=> Fix vagina not saving squirter status

src/com/lilithsthrone/game/character/GameCharacter.java
=> Fixed addiction time bug

src/com/lilithsthrone/game/character/npc/NPC.java
drops the multiplier from 10 to 2
=> Nerfs experience for winning comabt

src/com/lilithsthrone/game/character/npc/NPC.java
Removes the additional reference from the line
=> Nerfs essence awards after combat

src/com/lilithsthrone/game/dialogue/places/dominion/CityPlaces.java, src/com/lilithsthrone/game/sex/sexActions/universal/consensual/ConChairTop.java
=> Typo fixes

src/com/lilithsthrone/game/sex/sexActions/SexActionPresets.java
This just adds a few actions to the chair scenes that were missing. Main change is adding fingering so lesbian characters can actually _do_ something in these scenes, but also allow PCs with tails to use these.
=> Chair scene upgrades

src/com/lilithsthrone/game/sex/sexActions/baseActionsSelfPartner/PartnerSelfTailMouth.java, src/com/lilithsthrone/game/sex/sexActions/baseActionsSelfPlayer/PlayerSelfTailMouth.java
Similar to how you can with fingers.
=> Add one-shot actions to lubricate tails

src/com/lilithsthrone/game/sex/sexActions/baseActionsMisc/GenericOrgasms.java
This is a minor text change for when the PC takes a cumshot down their throat and should want it.
=> Make cum addicts enjoy swallowing cum

src/com/lilithsthrone/game/inventory/clothing/ClothingType.java
This fixes the new corset dress item. The main change is making it block the leg slot like other dresses do. Also includes reformatting the displacement section for consistency with other items (no functional changes) and replacing the ad-hoc colour lists with preset ones (although I question if it should really be restricted to black only by default).
=> Fix new corset dress clothing item

PULL_REQUEST_TEMPLATE.md
Asks for three pieces of information with the intent of speeding up acceptance of future PRs, It will also alert Innoxia that a PR was submitted.
=> Creates PR template

src/com/lilithsthrone/main/Main.java
```java
public static boolean isVersionOlderThan(String versionToCheck, String versionToCheckAgainst) {
String[] v1 = versionToCheck.split("\\.");
String[] v2 = versionToCheckAgainst.split("\\.");
try {
int v1i1 = Integer.valueOf((v1[0]+"00").substring(0, 3));
int v1i2 = Integer.valueOf((v1[1]+"00").substring(0, 3));
int v1i3 = 0;
int v1i4 = 0;
if(v1.length>2) {
v1i3 = Integer.valueOf((v1[2]+"00").substring(0, 3));
}
if(v1.length>3) {
v1i4 = Integer.valueOf((v1[3]+"00").substring(0, 3));
}
int v2i1 = Integer.valueOf((v2[0]+"00").substring(0, 3));
int v2i2 = Integer.valueOf((v2[1]+"00").substring(0, 3));
int v2i3 = 0;
int v2i4 = 0;
if(v2.length>2) {
v2i3 = Integer.valueOf((v2[2]+"00").substring(0, 3));
}
if(v2.length>3) {
v2i4 = Integer.valueOf((v2[3]+"00").substring(0, 3));
}
if(v1i1 < …
```
=> compare versions function cleanup

src/com/lilithsthrone/controller/MainController.java, src/com/lilithsthrone/rendering/RenderingEngine.java
This just adds tooltips to the map on the phone screen, indicating what type of place each cell is.
=> Add tooltips to map nodes

src/com/lilithsthrone/game/combat/SpellUpgrade.java
=> Corrects typos in air elemental upgrades

src/com/lilithsthrone/game/dialogue/story/PrologueDialogue.java
=> Prologue Typo fixes

src/com/lilithsthrone/game/character/GameCharacter.java
=> Use correct character's fertility in RollForPregnancy

lilithsThroneBuildTutorial.md
This is just a quick addition for people working with the Intellij IDEA IDE. It contains instructions for creating the project directly from Git or local files as well as setting up run configurations with and without Maven.
=> Added instructions for building with Intellij IDEA

src/com/lilithsthrone/game/character/PlayerCharacter.java, src/com/lilithsthrone/game/character/npc/dominion/Nyan.java, src/com/lilithsthrone/game/character/npc/dominion/SupplierLeader.java, src/com/lilithsthrone/game/character/npc/dominion/SupplierPartner.java, src/com/lilithsthrone/game/character/quests/Quest.java, src/com/lilithsthrone/game/character/quests/QuestLine.java, src/com/lilithsthrone/game/character/quests/QuestTree.java, src/com/lilithsthrone/game/character/quests/QuestType.java, src/com/lilithsthrone/game/dialogue/places/dominion/shoppingArcade/ClothingEmporium.java, src/com/lilithsthrone/game/dialogue/places/dominion/shoppingArcade/SupplierDepot.java, src/com/lilithsthrone/game/dialogue/utils/PhoneDialogue.java, src/com/lilithsthrone/rendering/RenderingEngine.java, src/com/lilithsthrone/utils/Colour.java, src/com/lilithsthrone/world/places/PlaceType.java
Makes the required modifications to have quest tree listed as a romance quest. Tested and checked for compatibility. Change is not SAVE compatible. Tested on 0.2.5.5
=> Changes Nyan's quest from Side to Relationship, with all references fixed

src/com/lilithsthrone/game/inventory/item/ItemType.java
Gotta get rid of copy pasta
Tested on 9f05f4642f520cba8db7a4b141e70ddc7fd17b3d (0.2.5.2)
=> Deduplicate book itemtypes

res/txt/places/dominion/lilayasHome/lilayasRoom.xml
One typo and some punctuation fixes in the panty masturbation scene and Rose's subsequent punishment. 
Sorry I didn't do that together with the other PR, I only just now looked at the scene in-game.
=> Panty Masturbation Punctuation Fixes

res/txt/characters/submission/batCavernBat.xml
Corrects a mention of 'she' instead of '[npc.she]'.
=> Fixed incorrect pronoun

src/com/lilithsthrone/game/dialogue/places/dominion/EnforcerHQDialogue.java
Fixes #530 By changing all required standing sex scenes to kneeling sex scenes in line with the written text
^
nope
Yes, 0.2.5.8
=> Update EnforcerHQDialogue to fix inconsistencies 

.gitignore
you can add files manually with git add -f, but I don't want to see my mods in my unchanged files list because this makes it hard to see what I changed
=> Mods added to gitignore

src/com/lilithsthrone/utils/ColourListPresets.java
Adds a list with all clothing colors and the metal colors, was requested by modding community.
=> Combination Clothing colors and metal colors list

src/com/lilithsthrone/game/character/GameCharacter.java
Fixes #667, by adding a null check into getName method.
=> Fix for saves in slaver alley stocks cell

src/com/lilithsthrone/game/character/npc/dominion/DominionSuccubusAttacker.java
=> Fix DominionSuccubusAttacker-slaves throwing nullpointers for TF items

src/com/lilithsthrone/game/dialogue/places/submission/SubmissionGenericPlaces.java
=> Fixes slime queen report back dialogue, as mentioned in #694

src/com/lilithsthrone/controller/MainController.java
=> Fix offspring renaming with enter key hardlocking game

src/com/lilithsthrone/game/Game.java, src/com/lilithsthrone/game/dialogue/SlaveryManagementDialogue.java, src/com/lilithsthrone/game/dialogue/places/dominion/shoppingArcade/SuccubisSecrets.java, src/com/lilithsthrone/game/dialogue/story/CharacterCreation.java, src/com/lilithsthrone/game/dialogue/utils/CharacterModificationUtils.java
=> Allow female beards when the option for female beards is enabled

src/com/lilithsthrone/game/character/body/valueEnums/Height.java
The voices in my head made me do this
=> fix wrongly named variable name because I like making daily pull requests

src/com/lilithsthrone/game/Game.java
=> Fix NullPointerException when entering the gambling den in new game

src/com/lilithsthrone/game/character/effects/StatusEffect.java
Doesn't fix any issue mentioned in issues but I spotted it myself soooooo why not?
=> Fix addiction timer displays to show 22:00 instead of 21:60

src/com/lilithsthrone/game/dialogue/places/dominion/CityPlaces.java
=> Fix missing explore button for CANAL_END

src/com/lilithsthrone/game/inventory/item/AbstractItemType.java
Because I feel these numbers shouldn't be duplicated.
=> deduplicate colourReplacement in AbstractItemType

src/com/lilithsthrone/game/character/body/FluidCum.java, src/com/lilithsthrone/game/character/body/FluidGirlCum.java, src/com/lilithsthrone/game/character/body/Vagina.java
Fixes #700. Fixes #502. Fixes #509. Fixes #526. Fixes #487.
(I'm typing that like that so it will auto-close all of them.)
=> Make vagina transformations affect girlcum type

src/com/lilithsthrone/game/dialogue/places/dominion/lilayashome/Library.java
Cleans up the Browse Books menu in the Library
^
no
-.2.6
=> Library Modifications

src/com/lilithsthrone/game/dialogue/places/dominion/lilayashome/LilayaHomeGeneric.java
And fixed Milk Self Girlcum option saying Milk Self Cum when energy too low
=> Fix self breast milking always emptying breasts

src/com/lilithsthrone/game/character/body/FluidCum.java, src/com/lilithsthrone/game/character/body/FluidGirlCum.java
=> Fix copying of fluidmodifiers in FluidStored constructor

src/com/lilithsthrone/game/Game.java, src/com/lilithsthrone/game/character/FluidStored.java, src/com/lilithsthrone/game/character/GameCharacter.java, src/com/lilithsthrone/game/character/Litter.java, src/com/lilithsthrone/game/character/PlayerCharacter.java, src/com/lilithsthrone/game/character/body/Body.java, src/com/lilithsthrone/game/character/body/valueEnums/BodyCoveringSkinToneColorHelper.java, src/com/lilithsthrone/game/character/effects/Addiction.java, src/com/lilithsthrone/game/character/markings/AbstractTattooType.java, src/com/lilithsthrone/game/character/markings/Tattoo.java, src/com/lilithsthrone/game/character/markings/TattooWriting.java, src/com/lilithsthrone/game/character/npc/NPC.java, src/com/lilithsthrone/game/character/npc/dominion/Nyan.java, src/com/lilithsthrone/game/dialogue/eventLog/SlaveryEventLogEntry.java, src/com/lilithsthrone/game/inventory/CharacterInventory.java, src/com/lilithsthrone/game/inventory/clothing/AbstractClothing.java, src/com/lilithsthrone/game/inventory/clothing/BlockedParts.java, src/com/lilithsthrone/game/inventory/item/AbstractItem.java, src/com/lilithsthrone/game/inventory/weapon/AbstractWeapon.java, src/com/lilithsthrone/game/slavery/MilkingRoom.java, src/com/lilithsthrone/game/slavery/SlaveryUtil.java, src/com/lilithsthrone/world/World.java
Mostly extracting getElementsByTagName in forloop out of the loop.
The rest of the performance seems to be caused by NPCs and garbage collection, as discussed on discord. Not much to do there, I'm afraid.
=> Save loading optimization

src/com/lilithsthrone/controller/MainControllerInitMethod.java, src/com/lilithsthrone/game/Properties.java, src/com/lilithsthrone/game/PropertyValue.java, src/com/lilithsthrone/game/character/GameCharacter.java, src/com/lilithsthrone/game/character/effects/StatusEffect.java, src/com/lilithsthrone/game/dialogue/utils/OptionsDialogue.java, src/com/lilithsthrone/game/dialogue/utils/PhoneDialogue.java
I've tested this to see if it works, but I'm not sure I missed anything. Would recommend merging before tuesdays so others can test as well.
=> Add cum regeneration mechanics toggle

src/com/lilithsthrone/game/character/GameCharacter.java, src/com/lilithsthrone/game/dialogue/places/dominion/lilayashome/Lab.java, src/com/lilithsthrone/game/dialogue/utils/InventoryDialogue.java, src/com/lilithsthrone/game/inventory/CharacterInventory.java
Greatly reduce the processing time for picking up/dropping a large number of items as well as the "extract arcane" option from Lilaya  (tested with 10.000 items) 
**Added these functions in the following classes**
_GameCharacter.java_
- bulkAddItem
- bulkRemoveItem
_CharacterInventory.java_
- bulkAddItem
- bulkRemoveItem
**Changed these functions in the following classes**
*InventoryDialogue.java*
- transferItems
- dropItems
- pickUpItems
*Lab.java*
- effects => Lines 1502, 1529 and 1562 (extracting 5, 25 and All essences)
No
Yes, 0.2.7. Extracted 10.366 …
=> Items adding loop replacement

src/com/lilithsthrone/game/character/fetishes/Fetish.java, src/com/lilithsthrone/game/combat/SpecialAttack.java, src/com/lilithsthrone/game/dialogue/utils/PhoneDialogue.java, src/com/lilithsthrone/game/sex/sexActions/SexAction.java, src/com/lilithsthrone/res/fetishes/fetish_cock_addict.svg, src/com/lilithsthrone/res/fetishes/fetish_dick_dealer.svg
Adds two new fetishes Cock addict and Dick dealer
Added fetishes, listed in phone menu, attached tease attacks, dialog was done by Nnxx
included in PR
yes 0.2.5.5
=> Adds Penis based fetishes

src/com/lilithsthrone/game/sex/SexPositionType.java
*Fixing some typos and grammar inconsistencies when switching positions*
*Replaced hardcoded verb with the .verb parser, added missing words where needed*
*No*
*Yes, 0.2.7.5*
*Nnxx*
...
*mlem*
=> Fixing typos

README.md
Just a very very small PR to help other devs / people who like building it on their own save some time.
There might be more to come ;)
=> Small note on JDK Compatibility in the README

src/com/lilithsthrone/game/dialogue/encounters/Encounter.java
Cleanup offspring encounters so that it is straightforward to add items to affect their encounter rate.
There should be no changes to the effect of the code. Duplicate code has been moved into helper functions.
No.
Yes. Tested against public master.
n/a
=> Parameterize and deduplicate code for offspring encounters.

src/com/lilithsthrone/game/character/GameCharacter.java, src/com/lilithsthrone/game/sex/PregnancyDescriptor.java
=> clean up pregnancy calculation

src/com/lilithsthrone/controller/xmlParsing/XMLLoadException.java, src/com/lilithsthrone/game/character/markings/AbstractTattooType.java, src/com/lilithsthrone/game/inventory/clothing/AbstractClothingType.java, src/com/lilithsthrone/game/inventory/clothing/BlockedParts.java, src/com/lilithsthrone/game/inventory/clothing/ClothingType.java, src/com/lilithsthrone/game/inventory/weapon/AbstractWeaponType.java
Based on #945 and #968. Feel free to read their descriptions. If this is merged, those can both be closed.
=> Improve mod error descriptions

src/com/lilithsthrone/game/dialogue/utils/PhoneDialogue.java
Deduplicate code in the Pregnancy Stats screen. Also adds a statistic for percentage of offspring met.
As in the purpose.
No.
Yes. Works at head.
n/a
=> Deduplicate code in the Pregnancy Stats screen. 

res/weapons/innoxia/arcanistStaff/arcanist_staff.xml, res/weapons/innoxia/crudeShield/crude_shield.xml, res/weapons/innoxia/dagger/dagger.xml, res/weapons/innoxia/pipe/pipe.xml, res/weapons/innoxia/scythe/scythe.xml
=> Fix typos in weapon files

src/com/lilithsthrone/game/character/race/Subspecies.java
This is a potential fix to the classpath problem some users are experiencing.
Need people who build with Eclipse to try and see if it works for them.
=> prelim_path_fix

res/mods/innoxia/items/clothing/rentalMommy/rental_daddy.xml, res/mods/innoxia/items/clothing/rentalMommy/rental_mommy.xml, src/com/lilithsthrone/game/inventory/clothing/AbstractClothingType.java, src/com/lilithsthrone/game/inventory/enchanting/ItemEffect.java
This change fixes the Rental Mommy encounter. Addresses #983.
Replaces out of date fetish references in the rental mommy and daddy XML files. Adds error message when attempting to import an invalid ItemEffect. Filters out null ItemEffect entries when loading clothing from XML.
No.
Yes, 0.2.12.6.
CognitiveMist|Phlarx
=> Fix Rental Mommy encounter

src/com/lilithsthrone/game/character/persona/Name.java
Increased the name lists by a considerable degree, increased the variety (fewer Carls!), and made the "prostitute" name generator occasionally produce "regular human" names (50% of the time) and vice versa (10% of the time). That last change can be undone if it's an issue, like if it'd be better to handle that elsewhere in the code.
No new graphical assets required.
(Gynoid / GearheadLydia#8498 on Discord)
=> Increased variety for Name.java

src/com/lilithsthrone/game/dialogue/DebugDialogue.java, src/com/lilithsthrone/main/Main.java
*Added three additional options in the debug menu.*
*In the "Misc." submenu, added :* 
*1) Ability to automatically complete Lilaya's enchantment quest*
*2) Ability to give yourself additional Epona stamps*
*3) Ability to automatically complete the slaver license quest*
(REMOVED) *Ability to get the KKP*
*No*
*Yes, 0.3 public build.*
*Nnxx*
=> More options in the debug menu

src/com/lilithsthrone/game/dialogue/utils/InventoryDialogue.java
Quality of life improvement.
Add the option to unequip all clothes when choosing the evening's attire
No
Yes, 0.3.0.7
Nnxx
=> Added option to unequip all clothes on character creation

src/com/lilithsthrone/controller/eventListeners/tooltips/TooltipInformationEventListener.java
Have the tooltip display the sizes of breasts and penis if known to the player.
Overloaded the getBodyPartDiv method to accept the size of a bodypart as a String parameter
No
Yes, 0.3.0.7
=> Added size display to tooltip

src/com/lilithsthrone/game/dialogue/places/dominion/lilayashome/Library.java, src/com/lilithsthrone/main/Main.java, src/com/lilithsthrone/world/WorldType.java
Adds half demon book and floor labels to locations
^
n
3.0
Rfpnj
=> Library and maps

src/com/lilithsthrone/controller/MainControllerInitMethod.java, src/com/lilithsthrone/game/Game.java, src/com/lilithsthrone/game/PropertyValue.java, src/com/lilithsthrone/game/character/npc/dominion/Brax.java, src/com/lilithsthrone/game/character/npc/dominion/Zaranix.java, src/com/lilithsthrone/game/dialogue/npcDialogue/dominion/AlleywayAttackerDialogue.java, src/com/lilithsthrone/game/dialogue/npcDialogue/dominion/AlleywayAttackerDialogueCompanions.java, src/com/lilithsthrone/game/dialogue/npcDialogue/dominion/HarpyAttackerDialogue.java, src/com/lilithsthrone/game/dialogue/npcDialogue/dominion/HarpyAttackerDialogueCompanions.java, src/com/lilithsthrone/game/dialogue/npcDialogue/submission/BatCavernAttackerDialogue.java, src/com/lilithsthrone/game/dialogue/npcDialogue/submission/BatCavernBatAttackerDialogue.java, src/com/lilithsthrone/game/dialogue/npcDialogue/submission/BatCavernSlimeAttackerDialogue.java, src/com/lilithsthrone/game/dialogue/npcDialogue/submission/TunnelAttackDialogue.java, src/com/lilithsthrone/game/dialogue/npcDialogue/submission/TunnelAttackDialogueCompanions.java, src/com/lilithsthrone/game/dialogue/npcDialogue/submission/TunnelImpsDialogue.java, src/com/lilithsthrone/game/dialogue/npcDialogue/submission/TunnelSlimeDialogue.java, src/com/lilithsthrone/game/dialogue/places/dominion/harpyNests/HarpyNestBimbo.java, src/com/lilithsthrone/game/dialogue/places/dominion/harpyNests/HarpyNestDominant.java, src/com/lilithsthrone/game/dialogue/places/dominion/harpyNests/HarpyNestNympho.java, src/com/lilithsthrone/game/dialogue/responses/Response.java, src/com/lilithsthrone/game/dialogue/utils/OptionsDialogue.java
*This adds one of some proposed optional difficulty/scenario options.*
*This difficulty option disables the "Spit" option in Forced TF dialogs.*
*no*
*by me, with various versions from 3.0+*
*none currently*
Since i'm not a native english speaker, the wording may seem a bit odd at times and i'll appreciate corrections/suggestions!
=> Add difficulty option: No Spitting

src/com/lilithsthrone/controller/MainControllerInitMethod.java, src/com/lilithsthrone/game/Game.java, src/com/lilithsthrone/game/PropertyValue.java, src/com/lilithsthrone/game/dialogue/utils/OptionsDialogue.java, src/com/lilithsthrone/game/sex/sexActions/SexActionInterface.java
*This adds one of some proposed optional difficulty/scenario options.*
*This difficulty option will disable the "Corruptive" actions during sex. Requirements may not be bypassed for corruption gain.*
*no*
*by me, with various versions from 3.0+*
*none currently*
Since i'm not a native english speaker, the wording may seem a bit odd at times and i'll appreciate corrections/suggestions!
=> Add difficulty option: No Sex Action Bypass

src/com/lilithsthrone/game/character/GameCharacter.java
Fixes slavery value for characters w/ retained virginity. Also adds an underflow check in there for good measure.
@Innoxia
=> Fix virginity cost errors

src/com/lilithsthrone/game/inventory/CharacterInventory.java
=> Clean character inventory

src/com/lilithsthrone/game/inventory/AbstractInventory.java, src/com/lilithsthrone/game/inventory/CharacterInventory.java
=> Character inventory cleaning

src/com/lilithsthrone/utils/Colour.java, src/com/lilithsthrone/utils/ColourListPresets.java
Adds a two new intermediate grey colors for clothing, and a "gunmetal gray" color for metals.
=> New grey colors

src/com/lilithsthrone/game/character/GameCharacter.java, src/com/lilithsthrone/game/character/body/valueEnums/LegConfiguration.java, src/com/lilithsthrone/game/character/npc/submission/Lyssieth.java, src/com/lilithsthrone/game/sex/sexActions/submission/SALyssiethSpecials.java
- **What is the purpose of the pull request?**
This is the proposed fix for issue #1127
- **Give a brief description of what you changed or added.**
'Become a demon' didn't take taur body into consideration. In addition to that I've made it, that the wing size is set to the minimum requirement to fly for the leg configuration.
- **Are any new graphical assets required?**
No
- **Has this change been tested? If so, mention the version number that the test was based on.**
Yes, 0.3.2.2 Alpha. Gone through 'Become a demon' and turning Lilaya and Meraxis into demons.
- **So we have a better idea of who you are, what is your Discord Handle?**
Stadler#3007
=> Fix taur to demon TF

res/clothing/norin/clover_clamps/clover_clamps.xml, res/clothing/norin/dildos/realistic_dildo.xml, src/com/lilithsthrone/game/occupantManagement/OccupancyUtil.java
Fixed XML tags for realistic dildo and clover clamps to allow sex equip and transparency.
Fixed typo in clover clamps' description.
Norin#3027
=> Fixed XML tags for realistic dildo and clover clamps

.classpath
Adding a set of clothing to the game
4 under-torso items
[Basty96.zip](https://github.com/Innoxia/liliths-throne-public/files/2922929/Basty96.zip)
Tested on v0.3.1.1
thebigdaddyking4536
=> Adding the Mommy's Lil' Toy and Daddy's Lil' Slut Shirts

src/com/lilithsthrone/game/dialogue/npcDialogue/dominion/HarpyAttackerDialogue.java, src/com/lilithsthrone/game/dialogue/npcDialogue/submission/BatCavernDialogue.java, src/com/lilithsthrone/game/dialogue/npcDialogue/submission/TunnelAttackDialogue.java
Fix attack dialogue problems for Harpy Nests and Bat Caverns
Added check for companion for places where NPE was possible.
Changed Harpy Nests dialogue ID to match files.
No.
After the change I ran through affected areas in v0.3.5.4 again
~Have no Discord yet~ TripleS941#0897
P.S. Oops, got my non-lewd account involved. But it is not immediately obvious from there, so oh well.
=> Fix attack dialogue problems

res/txt/characters/offspring/occupant.xml, res/txt/characters/offspring/slave.xml, res/txt/places/dominion/harpyNests/nympho.xml, src/com/lilithsthrone/game/character/GameCharacter.java, src/com/lilithsthrone/game/character/body/Body.java, src/com/lilithsthrone/game/character/body/types/NippleType.java, src/com/lilithsthrone/game/character/npc/NPC.java, src/com/lilithsthrone/game/dialogue/npcDialogue/dominion/AlleywayAttackerDialogue.java, src/com/lilithsthrone/game/dialogue/places/dominion/lilayashome/RoomPlayer.java, src/com/lilithsthrone/game/dialogue/places/submission/ratWarrens/CaptiveTransformation.java, src/com/lilithsthrone/game/dialogue/utils/UtilText.java, src/com/lilithsthrone/game/inventory/item/AbstractFilledCondom.java, src/com/lilithsthrone/game/occupantManagement/OccupancyUtil.java, src/com/lilithsthrone/game/sex/sexActions/baseActions/FingerBreastsCrotch.java, src/com/lilithsthrone/game/sex/sexActions/baseActions/TongueAnus.java, src/com/lilithsthrone/game/sex/sexActions/baseActions/TongueNippleCrotch.java, src/com/lilithsthrone/game/sex/sexActions/baseActionsMisc/GenericOrgasms.java
Fix a number of small bugs and typos
occupant.xml
slave.xml
nypmho.xml
Npc.java
RoomPlayer.java
TongueAnus.java
GenericOrgasms.java
AbstractFilledCondom.java
↳ Fixed typos and incorrect text parsing targets
GameCharacter.java
↳ Added null checks to places that were causing null pointer exceptions (the ones I noticed anyway)
↳ NPCs weren't reacting to penis reveal when gender wasn't matching because the character was already naked when the `getAppearsAsGender` check was executed. Added an overload to ignore genital visibility for these cases.
NippleType.java
↳ `getNameSingular` was returning a plural
AlleywayAttackerDialogue.java
↳ Offering body didn't account for lack of companions …
=> A collection of bugs and typos

src/com/lilithsthrone/game/sex/sexActions/SexActionPresets.java, src/com/lilithsthrone/game/sex/sexActions/baseActions/FingerNippleCrotch.java
Adds finger to crotch nipples interactions: pinching, milking and fingering.
Created a separate class for finger to crotch nipple interactions based on already existing FingerNipple class. Added these interactions into the game. Generated text and positioning restrictions work as they should.
No
Tested in 3.5.7
Rist
=> Add finger to crotch nipples interactions

src/com/lilithsthrone/game/character/npc/dominion/Vicky.java
fix empty stacks/incorrect prices in Vicky's shop: #1275
I have Vicky remove all sold items from the ...ForSale lists when all items are sold.
no
yes, v0.3.5.8
none
=> Fix empty stacks in Vicky's shop

res/txt/misc/prologue.xml
What is the purpose of the pull request?
Fix the issue where the NPC in the prologue knows about the MC's penis when this shouldn't be the case.
Give a brief description of what you changed or added.
Add textual changes based on isFeminine, isPenisBulgeVisible and isTesticleBulgeVisible
Are any new graphical assets required?
No
Has this change been tested? If so, mention the version number that the test was based on.
Yes, version 0.3.5.8
There's a surprising number of possible combinations to try out!
=> Changed text in prologue for MC as a trap.

src/com/lilithsthrone/game/character/GameCharacter.java
=> fixed slime to angel loophole

src/com/lilithsthrone/game/character/body/Body.java
Change "procude" to "produce" in Body.java
Typo fix only
Nope.
Not tested, pretty obvious what the problem is
=> Typo fix procude -> produce

src/com/lilithsthrone/game/character/npc/dominion/Amber.java
Fixes inability to orgasm when having sex with Amber with no neck clothing, by adding a null check.
Fix checked on v0.3.6.8
Discord Handle: TripleS941#0897
=> Fix Amber's level drain

src/com/lilithsthrone/world/WorldType.java
Fix #1327 
Added a null check
No
Yes, against 0.3.7.3
none
=> Fix Phone menu in Shopping Arcade

res/txt/characters/raceInfo.xml, res/txt/encounters/dominion/enforcerAlleyway.xml
Fix minor text issues in dialogues
In the Enforcer Alleyway dialogue the reference should be to the npc3 (character being enslaved), not to the Enforcer that is present
Fixed some typos in the race info text
No
Yes, tested in 0.3.8.9
=> Fix minor issues in dialogues

res/txt/places/submission/gamblingDen/main.xml
"dno't" > "don't"
"..doing it, than?" > "..doing it, then?"
Edit: "The Enforcers have **places** selling restrictions on the two of them." > "..placed.."
=> Minor Rat-Quest Typos

src/com/lilithsthrone/game/inventory/enchanting/ItemEffectType.java, src/com/lilithsthrone/game/inventory/item/ItemType.java
- If you want quick feedback, you can use Innoxia, or jump on the Lilith's Throne discord and send Innoxia a PM.
=> added some missing unit parsers

res/txt/encounters/dominion/alleywayAttack.xml, res/txt/encounters/dominion/harpyAttack.xml, res/txt/encounters/submission/batCavern/bat.xml, res/txt/encounters/submission/batCavern/batCompanions.xml, res/txt/encounters/submission/batCavern/generic.xml, res/txt/encounters/submission/batCavern/genericCompanions.xml, res/txt/encounters/submission/batCavern/slime.xml, res/txt/encounters/submission/batCavern/slimeCompanions.xml, res/txt/encounters/submission/tunnelAttack.xml, res/txt/encounters/submission/tunnelAttackCompanions.xml
Fix missing verb for issue #1291 
A word
No
No testing needed, text-only change
=> Add missing verb for #1291

src/com/lilithsthrone/game/character/body/Body.java, src/com/lilithsthrone/game/character/race/AbstractSubspecies.java
Improve performance by caching subspecies variables and only doing a recalculation when needed.
Save subspecies and return it instead of doing the calculation again and again. Reset subspecies when needed.
Removed a space in an assignment in Body.java that was not really necessary.
No
Yes, tested with version 0.3.13
AceXP#0930
=> Cache sub species

src/com/lilithsthrone/game/character/body/Body.java
Appearance for feral legs were hardcoded and didn't take various leg configurations into account. Fixed that.
In addition to the fix mentioned above I switched from string concatenation to chain of appends in the chunks I updated.
No.
Yes, 0.3.13 Alpha
`@Stadler#3007`
=> Appearance fix for feral legConfigurations

res/txt/places/dominion/harpyNests/generic.xml, res/txt/places/dominion/harpyNests/helena.xml, res/txt/places/submission/batCaverns.xml, src/com/lilithsthrone/controller/MainController.java, src/com/lilithsthrone/game/dialogue/places/dominion/harpyNests/HarpyNestsDialogue.java, src/com/lilithsthrone/game/dialogue/places/dominion/zaranixHome/ZaranixHomeGroundFloor.java
Ryus don't use wings to fly, even if they would have wings. Fixed that so that the wings aren't mentioned in such scenes, when the player can fly without wings.
I might have overlooked a few scenes where it is still mentioned, that the player uses his/her wings, but most scenes should now play correctly if the player can fly without wings.
In the `.java`-files I've modified I've used chain of appends instead of string concatenation where applicable.
No.
Yes, 0.3.13 Alpha
`@Stadler#3007`
=> To flap or not to flap

res/txt/places/dominion/warehouseDistrict/kaysTextiles.xml, src/com/lilithsthrone/game/dialogue/places/dominion/slaverAlley/BountyHunterLodge.java, src/com/lilithsthrone/game/dialogue/places/dominion/warehouseDistrict/KaysWarehouse.java
Fix parsing errors, typos and minor issues in the new warehouse quest
Fix some his/her errors after feminising Kay.
Fix missing brackets in parser command
Swap searching and searched tags
Fix detection of cage/buttplug worn or not
No
Yes, tested with 03.14
AceXP#0930
=> Dobermanns
