Innoxia/liliths-throne-public

src/com/base/game/combat/SpecialAttack.java

The issue was caused by reusing the same stringbuilder, so I redeclared it as a local variable. Cleaner solutions might be available but this works.

fix special attack descriptions not showing when performing the attack

---

src/com/base/game/dialogue/utils/PhoneDialogue.java
src/com/base/res/css/webView_stylesheet.css
src/com/base/res/css/webView_stylesheet_light.css

This doubles the height if there are more than 15 colors for a piece of clothing.
In the future, you'd want to have a solution that dynamically scales instead of just doubling the height (mainly because this will break for 31 colours), but it should be fine for now.

hackfix clothing colors in encyclopedia - needs a proper fix later

---

src/com/base/controller/eventListeners/InventoryTooltipEventListener.java
src/com/base/game/character/GameCharacter.java
src/com/base/game/dialogue/utils/InventoryDialogue.java
src/com/base/game/inventory/AbstractCoreItem.java
src/com/base/game/inventory/CharacterInventory.java
src/com/base/game/inventory/clothing/AbstractClothing.java

this still needs extensive testing to make sure it really doesn't add any more bugs.
Bugs fixed:
- Take all from floor doesn't handle stackables well if your inventory is full
- Take all weapon doesn't work if inv is full?
- Jinxed items don't stack when unjinxed
- You can't store stackables if the area is full
- Unidentified items will show their state in the buyback menu
- Jinxed items can't be selected if you're carrying a dye brush and just identified them
- Unidentified items will sell for their real value and not the fixed value you get for an unidentified item
- That includes the "vendor will buy for x" text (not overlay) and the button
- "These items will disappear when you leave the area" when trading on a tile with dropped stuff
- Can't buy/buyback a stackable with full …

Fix inventory bugs

---

src/com/lilithsthrone/game/character/body/Body.java

Wings which do not allow flight (currently, demon wings and NONE) should never be described as allowing flight if they are of average size or larger.

Fix demon wings incorrectly described as allowing flight

---

src/com/lilithsthrone/res/css/webViewAttributes_stylesheet.css
src/com/lilithsthrone/res/css/webViewAttributes_stylesheet_light.css
src/com/lilithsthrone/res/css/webViewButtons_stylesheet.css
src/com/lilithsthrone/res/css/webViewButtons_stylesheet_light.css
src/com/lilithsthrone/res/css/webViewMenu_stylesheet.css
src/com/lilithsthrone/res/css/webViewMenu_stylesheet_light.css
src/com/lilithsthrone/res/css/webViewResponse_stylesheet.css
src/com/lilithsthrone/res/css/webViewResponse_stylesheet_light.css
src/com/lilithsthrone/res/css/webViewTooltip_stylesheet.css
src/com/lilithsthrone/res/css/webViewTooltip_stylesheet_light.css
src/com/lilithsthrone/res/css/webView_stylesheet.css
src/com/lilithsthrone/res/css/webView_stylesheet_light.css

This branch adds Carlito as an alternative font for Calibri in the CSS. This is necessary to display the interface correctly when the game is run natively on Linux. (There's no Calibri and the text becomes too large for the buttons.) Carlito is supposed to be an open-source alternative to Calibri with the same font metrics, so no sizes change.
Note: The .jar from the website has been tested and works correctly (except for the font issue) on Ubuntu 17.10, so you may want to add that info on the website. (It used to crash in an earlier version, but I don't know which of the many package updates has fixed the issue.) The following packages and their dependencies have to be installed for the fixed version: `openjfx fonts-crosextra-carlito`.

Linux font compatibility

---

src/com/lilithsthrone/game/inventory/clothing/ClothingType.java

Striped leggings, panties, and bra incorrectly use BASE_BLUE_LIGHT and BASE_PINK_LIGHT, causing the color viewer for these clothing items to erroneously display both the BASE and CLOTHING variations of these colors. This fixes that issue.

Changing striped clothing items to use CLOTHING instead of BASE colors.

---

src/com/lilithsthrone/game/character/GameCharacter.java
src/com/lilithsthrone/game/sex/sexActions/universal/consensual/ConChairTop.java

Currently, if a player is getting tail-pegged while on top during chair sex, they have no ability to stop it, which in turn means no changing positions. This fixes that.
Tested with Kate.
Also correct pulling the wrong orifice/penetration description on initial penetration.

Couple of sex fixes

---

src/com/lilithsthrone/game/combat/Attack.java

This is a fix for the bug where the attacker and defender are the wrong way around when comparing orientation to femininity.

Orientation Bug

---

src/com/lilithsthrone/game/inventory/clothing/AbstractClothing.java

The game was only checking _default_ colours on import, not available dye colours. So, if you dyed your clothes a colour they couldn't generate with, the colour wouldn't load.

Fix for clothing colours bug

---

src/com/lilithsthrone/game/inventory/item/ItemEffect.java

This just adds a check on importing ItemEffects to see if they refer to strength, fitness, or intelligence, and if so translate that to physique or arcane as appropriate. With this, players with saves from before the change should hopefully keep any potions they had made.

Enchantment effect translate for old saves

---

src/com/lilithsthrone/game/character/PlayerCharacter.java

This simply skips over any nulls that might get into booksRead, stopping them from blocking export. It doesn't address why nulls might be getting into booksRead to begin with, just stops them from doing the damage if they do.

Fix for export error with nulls in booksRead

---

src/com/lilithsthrone/game/dialogue/npcDialogue/CultistDialogue.java

The cultist sealed scene had the wrong starting positions, and Sex.updateAvailableActions() does _not_ handle this gracefully. I've corrected the bad positions, but sex positions should really have default positions to fall back on in case this happens again.

Fix for fatal bug on cultist sealed scene

---

src/com/lilithsthrone/game/inventory/item/ItemEffect.java

It is Attribute.MAJOR_ARCANE, but ItemEffectType.MAJOR_ARCANE doesn't exist. Potions still use ATTRIBUTE_ARCANE for the itemEffectType field.

Fix for importing potions

---

src/com/lilithsthrone/game/character/body/Body.java
src/com/lilithsthrone/game/character/body/types/BodyCoveringType.java
src/com/lilithsthrone/game/character/body/valueEnums/CoveringModifier.java

Adds a number of modifiers to some makeup types, and enables their use in the description pages. I'm not an expert on makeup, so there might be more that could be added.

Add various modifiers to makeup coverings

---

src/com/lilithsthrone/game/character/effects/StatusEffect.java

Previously, Alexandria's "human" status effect said "You're a human, just like every other person in this world."

Prologue human race handles NPCs now

---

src/com/lilithsthrone/game/sex/sexActions/baseActionsMisc/GenericOrgasms.java

This refactors the GenericOrgasms.isGenericPartnerCumTargetRequirementsMet method, hopefully making clearer what it's doing, but more importantly removing the requirement that the partner be penetrating the player. This should fix the bug where, if the NPC is not penetrating the player, they have no cum actions and fall back to the PARTNER_ORGASM_GENERIC action, which always uses the first available cum target (rather than a random one), and also doesn't apply the dirty effect properly to either the player, or themselves if using my new cum targets from #208.

Refactor GenericOrgasms.isGenericPartnerCumTargetRequirementsMet

---

src/com/lilithsthrone/game/inventory/clothing/ClothingType.java

Items of clothing are tagged for coverage for things like genitals or nipples, which need to be blocked for sex actions, but they have no coverage for things with no sex actions like stomach, back, or hair.
This adds such slots, which should fix the bug where you cum on a character's back or stomach and it dirties the body _through_ the clothes without touching the clothes.

Add coverage to clothing for slots with no sex actions

---

src/com/lilithsthrone/game/sex/OrgasmCumTarget.java
src/com/lilithsthrone/game/sex/SexPositionSlot.java
src/com/lilithsthrone/game/sex/sexActions/baseActionsMisc/GenericOrgasms.java

This adds new cum targets for a character in a reclining position (the bottom in missionary or cowgirl, for example) to cum on themselves rather than on their partner or the floor.

Add cum targets for characters cumming on themselves

---

src/com/lilithsthrone/game/inventory/item/AbstractItem.java
src/com/lilithsthrone/game/inventory/item/ItemEffect.java

Test for the damage/resistance stat for attacks when importing potions. I don't think this has an equivalent in the new versions, so these effects are simply dropped.

Add check for new potion enchantments

---

src/com/lilithsthrone/game/character/GameCharacter.java

When importing from saves from before the attribute renames, intelligence really shouldn't be translated to arcane; doing this gives all imported characters arcane ability, which the majority of them shouldn't have.

Remove translation of INTELLIGENCE to MAJOR_ARCANE

---

src/com/lilithsthrone/game/dialogue/places/dominion/harpyNests/HarpyNestsDialogue.java

Increases Flame award from Harpy quest to 5000 flames, which is now 1/3 of the cost for Scarlett, instead of 1500 (1/10 the cost). Where you do get a good deal of essences during the quest, with the increased need for them for use with enchanting it balances out a bit better.

Update Angry Harpy Quest to reflect new pricing scheme

---

src/com/lilithsthrone/game/sex/Sex.java

Change what triggers the "Frustrated" status effect from "did not cum" to "ended sex just before orgasming". Also removed the requirement to not be in resisting pace; even if unwilling, being taken right to the edge and then stopped is going to be frustrating.

Change what causes the "Frustrated" status effect

---

lilithsThroneBuildTutorial.md
pom.xml

This is to compensate for adding the new `/res` folder a couple of versions back and fix the other path which I think I wrote wrongly
I've also added some instructions for using Maven to the build tutorial

Maven resources fix and instructions

---

src/com/lilithsthrone/game/dialogue/utils/UtilText.java

Creating a line of speech by femininity would only use the regular masculine or feminine colours, even if fed a plus version of masculine or feminine; now all five femininity variants work fine for that purpose.

Fix speech parsing by femininity

---

src/com/lilithsthrone/game/Game.java

Previously, loading the game would advance time from the point the game was saved.

Fix for loading the game advancing time

---

src/com/lilithsthrone/game/dialogue/story/CharacterCreation.java

BodyChanging target needs to be set to the player _before_ gender selection, fix for #204.

Set BodyChanging target to player earlier in character creation

---

src/com/lilithsthrone/game/inventory/clothing/AbstractClothing.java

Fix for #310, checks that imported clothing displacements are valid on import.

Fix for bad displacement imports crashing after sex

---

src/com/lilithsthrone/game/dialogue/npcDialogue/SlaveDialogue.java

This adds a management tab to the dialog when talking to a slave. It's a little quirky, as the "back" buttons on the management dialogs dump you back to the main room dialog rather than the slave dialog, but other than that it seems to work fine.

Add management tab to slave interface

---

res/txt/characters/dominion/nyan.xml
res/txt/places/dominion/shoppingArcade/clothingEmporium.xml
res/txt/places/dominion/shoppingArcade/dreamLover.xml
res/txt/places/dominion/shoppingArcade/suppliersDepot.xml

Dialogue tags!
After looking it up, it seems the rules my old English teacher taught us still hold true. So, no commas for narration, dialogue tags that sit between two independent clauses end on a fullstop etc. [This thing](http://theeditorsblog.net/2010/12/08/punctuation-in-dialogue/) summarises it nicely.
The question is though what you constitute as a dialogue tag, people seem to argue about that. 
This is just my own opinion, but things like "he smiles" or "she frowns" are not tags, while "he laughs/growls/sighs" can be, depending on context. Like, you can laugh out words or growl them, but you can't smile a sentence. So anything that affects the words, the tone, intonation or pace, can be a tag. But it could also not be, if it is a separate action. That's just my two cents, there …

Punctuation fixes

---

src/com/lilithsthrone/game/character/body/Breast.java

This allows Breast.setSize to accept a null value for the owner parameter, in a similar manner to how Ear.setType and Tail.setType work.

Fix for Breast.setSize

---

src/com/lilithsthrone/world/places/PlaceType.java

This just changes the background colour for the Harpy Nest entrance to match the darker colour the streets under the nests have.

Fix background colour for Harpy Nest entrance

---

src/com/lilithsthrone/game/character/GameCharacter.java

This changes ingestFluids to only show the "new addiction" dialog if the ingesting character isn't already addicted to the fluid, and to otherwise always show the "satisfied craving" dialog if the ingesting character is addicted.
This makes it a little cleaner to use the addiction system, since before if you fed an addicted character with an addicting version of a fluid, it would show the "new addiction" dialog every time.

Addiction patch 2

---

src/com/lilithsthrone/game/character/npc/dominion/HarpyNestsAttacker.java

Curious how harpy generation works, I discovered it's determined solely by femininity - this produced the situation where a player could set their gender preferences to 100% shemales or traps, and harpies would all generate as female. This doesn't seem right, if a player has a preference for cocks, they should _get_ cocks. This will fix that issue.

Rework harpy body selection

---

src/com/lilithsthrone/game/character/npc/dominion/Lilaya.java

This fixes the bug introduced in commit 7f723ab where Lilaya will immediately bail out of Geisha submissive sex. The simplest solution seemed to be overriding her isAttractedTo() method to always return true.
No new graphical assets are required, this is simply a bugfix.
Change has been tested on 0.2.3.1. Lilaya no longer bails out due to not having the incest fetish.
@Innoxia: I think you'll want to grab this one for sure before the next release.
Fixes issue #360

BUGFIX: Fix Lilaya Geisha submissive sex

---

src/com/lilithsthrone/game/character/body/valueEnums/BodyMaterial.java
src/com/lilithsthrone/game/dialogue/utils/UtilText.java

This expands BodyMaterials so that they can have more than one descriptor, and adds parser functionality to refer to a character's BodyMaterial and its parts. Several of the BodyMaterials have been edited to fit with this new functionality.
If one descriptor is provided, BodyMaterials act as before. This applies to slime and rubber, currently.
If two descriptors are provided, BodyMaterials can have a noun and an adjective as descriptors. This applies to fire and ice, currently.
Otherwise, a noun and an adjective are expected for each of the following:
- Skin on humanoid body parts
- Skin on nonhumanoid body parts
- Internal flesh of orifices on humanoid body parts
- Internal flesh of orifices on nonhumanoid body parts
- Hair on top of the head (Ponytails, hime cuts, etc.)
- Hair on …

BodyMaterial expansion, parser commands

---

src/com/lilithsthrone/game/combat/SpellUpgrade.java

Just fixed 2 mentions of target when it should have been caster.

Fix typos in telepathic communication upgrades

---

src/com/lilithsthrone/game/dialogue/story/CharacterCreation.java

Strong men get gold, weaker men get silver same as the feminine characters.
Added two lines to the character creation dialog to add rings to the masculine characters
NO
Yes, 0.2.3.5

Adds rings to masculine Characters during creation

---

src/com/lilithsthrone/game/character/GameCharacter.java
src/com/lilithsthrone/game/character/effects/StatusEffect.java

Fix #443 by relocating intoxication percentage logic to a single location (GameCharacter), fixing any issues with it there, and then having everything use the GameCharacter's method of calculating intoxication percentage
Tested on ad09d08835661cc5c983016a31025e52f79e4652 which is 0.2.4.5

Fix intoxication percentage logic

---

src/com/lilithsthrone/game/character/body/Body.java
src/com/lilithsthrone/game/character/body/FluidCum.java

This fixes #427 - most of the bug is already described there. Basically, the game used to load modifiers from a type, but then also from the modifiers themselves. This PR alters the loading to only add modifiers if they're not present already, and if the modifiers are present and the savefile says the character doesn't have them, they're removed.
Tested on ad09d08835661cc5c983016a31025e52f79e4652 (0.2.4.5), although I didn't test all the cases.
**As a result, This needs a proper review.**

Remove modifiers during loading if the savefile explicitly mentions them as false

---

src/com/lilithsthrone/controller/MainController.java
src/com/lilithsthrone/game/dialogue/utils/EnchantmentDialogue.java

As discussed in #283, this adds a screen to the enchanting UI where you can save/load the current list of enchanting effects to files. There is one issue, since the effect type must match between the item type being enchanted and the item type in the file, you can't load a potion saved using the "Sexual" type potion when enchanting a "Corruptive" type potion, as these are technically different ItemEffectTypes even though all effects a "Sexual" type potion can have, a "Corruptive" type potion can _also_ have. Likewise, a transformation potion saved using a cow-morph item can't be loaded to enchant a dog-morph item even if you aren't using any cow-specific effects. I'll be looking at ways to fix this soon, I hope.

Saveable recipes for enchanting

---

src/com/lilithsthrone/game/dialogue/utils/UtilText.java

Improve performance and fix crashes/infinite loops with npcs being called [npc.name].
I described this on discord:
parsing works by scanning the entire string, then looking for the first executable section, then doing that and starting over from the beginning.
Lower bound complexity is O(n); it has to check each character to find 0 ['s.
Upper bound is infinite loop, as seen when pc.name is [pc.name].
Pretending there are no infinite loops and commands don't output commands,
Upper bound would be O(n^n)
thus if we feed it large slabs of text we're screwed
but here's what I wonder
provided that the output shouldn't contain commands...
why would you need to parse the things you already parsed?
Thus I will try to see what happens if I get rid of the "and start over from the beginning"
``` …
```

Increase utiltext parse performance

---

src/com/lilithsthrone/game/dialogue/utils/UtilText.java

Should not negatively affect performance too much
https://cdn.discordapp.com/attachments/337330311694254121/445193814454566922/unknown.png
" [lilaya.speech([pc.Name]! E-Erm, w-we were just... Doing an experiment! Yes! Isn't that right, Rose?!)]"
Seems we were wrong in #472 that there were no nested commands

Re-allow parsing nested commands; fixes issues with Lilaya's Lab scene

---

src/com/lilithsthrone/game/character/GameCharacter.java
src/com/lilithsthrone/game/dialogue/utils/EnchantmentDialogue.java
src/com/lilithsthrone/game/dialogue/utils/InventoryDialogue.java

mainly to fix a possible null pointer when enchanting offhand weaponry (yes, you can't do this, but the code seems to want to handle it) without a main weapon equipped

Create method hasWeaponEquipped in GameCharacter for cleanup

---

src/com/lilithsthrone/controller/MainController.java

Opening character examination in intro causes saved dialogue node
Opening options causes saving current dialogue node
This overwrites the previous dialogue node, making you stuck
Solution; don't save when opening options when in character examination in intro

fix softlock caused by opening options menu during examining alexandria in intro

---

src/com/lilithsthrone/utils/Util.java

I simplified down some of the logic and added a single method `insertIntoSentence` that does most of the stuff that's repeated in those other methods.
When words are inserted at the beginning of sentences it now lowercases the following word that was originally the start of the sentence.
An edge case I'm not sure how to deal with is if sentences start with names or titles (like your nickname).
Edit: Maybe a simpler method to avoid unwanted decaps would be to avoid inserting into the start of a sentence entirely? If correcting caps is wanted, this seems like the only reasonable way to ensure correctness.

Fix inserted bimbo/sex/muffled/drunk words breaking capitalisation

---

src/com/lilithsthrone/game/sex/Sex.java

This reworks the repeat actions sex tab. Changes:
- Actions are now sorted by recentness, with most recent actions listed first
- Actions are no longer greyed out; they just don't appear
- Actions that are unavailable are not forgotten - for example, actions that require you to be fingering someone, like "Rough Fingering" or "Clit Focus" will no longer disappear from the recent actions tab if you stop fingering someone and then start again.

Rework repeat actions tab

---

src/com/lilithsthrone/game/dialogue/utils/UtilText.java

In an attempt to reduce memory footprint. Attempt to properly fix nested command parsing, mainly by checking how many braces the input has. If it has one set of braces, the output is not parsed again. This means no more [npc.name] outputting [npc.name] shenanigans.
It also seems to improve performance for the fetishes screen, although this is slightly less noticeable than before. What it should mostly do is reduce the amount of memory needed.
Tested on 9f05f4642f520cba8db7a4b141e70ddc7fd17b3d (0.2.5.2 release)

Convert UtilText.parse from recursive to iterative

---

res/txt/characters/dominion/rentalMommy.xml

Just some quick dialogue punctuation corrections for the Mother's Day event.
Remember, a dialogue tag coming after the dialogue itself begins in lowercase, even if the dialogue ended on a question mark, exclamation mark or ellipsis.

Rental Mommy Punctuation Fixes

---

src/com/lilithsthrone/game/character/body/types/HornType.java
src/com/lilithsthrone/game/inventory/enchanting/AbstractItemEffectType.java

Fixes HornType.NONE showing up as an option for enchanting. Horn removal can be done by selecting the remove option.

Only show horns which are real as selectable for transformation

---

src/com/lilithsthrone/game/dialogue/npcDialogue/dominion/DominionSuccubusDialogue.java

Fix for #490 and #519. The choices for "No dick" and "Vagina" didn't actually do anything, presumably a relic of when the encounter was _just_ succubi, and they would have female genitals to begin with.

Fix Incubus ignoring genital feminisation choices

---

src/com/lilithsthrone/game/dialogue/utils/UtilText.java

fixed by always setting npc list (because conditional commands wouldn't do this)
See also discord: 
So basically as far as I see it you start in getCumQuantityDescription
there you want to parse the  #IFnpc1.isPlayer#THENyour#ELSE[npc1.name]'s#ENDIF
then you go to the parser with the UtilText.parse call(edited)
there you quickly find the #IF and the rest, so you go to conditional syntax parsing...
npc1 is not the player, when you in parseConditionSyntaxNew try to find the parsing target from the tag "npc1" via ParserTag.NPC, so npc1.isPlayer is false
then you parse the ELSE segment, which is a non-conditional
so we go to parseSyntaxNew
the first thing we do there is update the character list------
with a single character.
...
gotcha.
Imagine two characters orgasm, one after the other …

Fix orgasm descriptions mention player's name

---

src/com/lilithsthrone/controller/eventListeners/InventoryTooltipEventListener.java

I'm not sure that passing null for the primary and secondary colours is correct, but I can see the different colours in encyclopedia now. Fixes #668.

Fix encyclopedia weapon colours

---

src/com/lilithsthrone/game/character/GameCharacter.java

Fixes #666 , Player was given UNEMPLOYED which raised lust resist by 5, then the bonus attribute map is reset, then the history is set to what it should be, which "reverses" the effects, leading to -5 lust resist.

Fix history status effect not properly applied

---

src/com/lilithsthrone/game/Game.java
src/com/lilithsthrone/game/dialogue/SlaveryManagementDialogue.java

Fixes #531. Was caused by SlaveryManagementDialogue keeping a reference to all the cells within Lilaya's home, even after hitting new game (Thus also being a memory leak of sorts). Now creating a new game clears the list. It's not the most clean solution but I don't feel like digging the important cells cache out of the Slavery system for now.

Fix slavery upkeep persisting across new games

---

res/txt/characters/submission/batCavernBat.xml
res/txt/characters/submission/batCavernDefault.xml
res/txt/characters/submission/batCavernSlime.xml
res/txt/places/submission/batCaverns.xml
res/txt/places/submission/slimeQueensLair.xml
res/txt/places/submission/submissionPlaces.xml
res/txt/places/submission/tunnelSlime.xml
src/com/lilithsthrone/game/dialogue/npcDialogue/submission/BatCavernAttackerDialogue.java
src/com/lilithsthrone/game/dialogue/npcDialogue/submission/BatCavernBatAttackerDialogue.java
src/com/lilithsthrone/game/dialogue/npcDialogue/submission/BatCavernSlimeAttackerDialogue.java
src/com/lilithsthrone/game/dialogue/npcDialogue/submission/TunnelAttackDialogue.java
src/com/lilithsthrone/game/dialogue/npcDialogue/submission/TunnelSlimeDialogue.java
src/com/lilithsthrone/game/dialogue/places/submission/SlimeQueensLair.java

We're getting there.
Dialogue punctuation corrections for the Slime Queen quest and some other stuff around Submission. I'll look into the Gambling Den another time.
I'm sure I missed some, and there're the usual debates about whether something should be considered a dialogue tag or not. In which case it's mostly up to preference.
I don't know why it keeps creating an extra empty line after `</dialogue> `at the end of the .txt files and I can't seem to make it stop doing that.

Punctuation Fixes for Slime Queen Quest

---

src/com/lilithsthrone/game/dialogue/utils/UtilText.java
src/com/lilithsthrone/game/sex/sexActions/baseActionsMisc/GenericOrgasms.java

Adds some parser commands that will simplify creating dialogue. GenericOrgasms.java is full of if/else statements where the only difference between the player and NPC dialogue is the person of the verbs and possibly second/third person pronouns. This accounts for both of those options, and also includes a sample of the kind of code reduction this pull request will allow. I can do a series of follow-up commits to take full advantage of these new features, but will want this merged before I start that work. This was originally #358, but it sat unmerged so long that it became impossible to merge due to changes in UtilText.
Improves some existing dialogue parsers and adds others. These parser …

Dialogue improvements (New Parser Options)

---

src/com/lilithsthrone/game/dialogue/utils/CharacterModificationUtils.java

During character creation, there is really no point in drawing glow buttons that are always greyed out beneath the skin, hair and eye colour selectors.

Remove glow buttons in character creation

---

src/com/lilithsthrone/game/character/body/types/BodyCoveringTemplate.java
src/com/lilithsthrone/game/character/body/types/BodyCoveringTemplateFactory.java
src/com/lilithsthrone/game/character/body/types/BodyCoveringType.java

To get rid of duplication and simplify the process of adding new races.
I allowed BodyCoveringType to be created based on a template, then made a template factory, allowing me to deduplicate values normally passed to the normal constructor.
I booted the game up, went into some transformation menus, seems to work fine. Didn't test in detail.
I'd like to see this reviewed, specifically with regards to the names of the methods in the BodyCoveringTemplateFactory

Clean BodyCoveringType via BodyCoveringTemplateFactory

---

src/com/lilithsthrone/controller/TooltipUpdateThread.java
src/com/lilithsthrone/controller/eventListeners/InventoryTooltipEventListener.java
src/com/lilithsthrone/controller/eventListeners/TooltipInformationEventListener.java
src/com/lilithsthrone/controller/eventListeners/TooltipResponseDescriptionEventListener.java
src/com/lilithsthrone/controller/eventListeners/information/CopyInfoEventListener.java

Change `ToolTipUpdateThread` to not create a new Java thread with every Tooltip display
Changed the Tooltips to not run on a new thread every time, and instead run on the JavaFX thread.
No
Tested on 2.6.5 and on the `dev` branch
@Alaco

Fixed ToolTipThread to not create a new thread with evvery display

---

src/com/lilithsthrone/game/sex/SexFlags.java
src/com/lilithsthrone/game/sex/sexActions/baseActionsMisc/GenericOrgasms.java

This adds an action to deny an NPC's orgasm. The descriptions are basic and probably want expanding, but I'm pretty confident on the mechanics of it. I haven't added an action for NPCs to deny the player yet as that seems to work a bit differently.

Generic orgasm denial

---

src/com/lilithsthrone/game/character/npc/NPC.java
src/com/lilithsthrone/game/dialogue/utils/CharactersPresentDialogue.java
src/com/lilithsthrone/rendering/RenderingEngine.java

When the race was concealed, the tile text would still display the race.
After the second commit
There was more to it then I thought. Now when the race is concealed:
-The character present window won't show stats
-The character present window won't show the race or the name of the person
-The icon shown is now a question mark(already implemented)
-The character present dialogue won't show the character detail
The only thing that I think is missing is the stats window in the character present dialogue
I'm not sure of what direction to take with this window, remove it? Remove all the information from it?
PS. Right now no generated character or unique character return true at `isRaceConceal()` method you need to edit an npc to test the feature

Further implement the conceal system

---

src/com/lilithsthrone/game/inventory/enchanting/AbstractItemEffectType.java

Clothing enchantments can't currently alter vaginal urethral stats; there's no way in the UI to do so, and even 'cheated' in via save editing, they don't show up in the items and are removed if put in. With these changes to AbstractItemEffectTypes, they can be enchanted in clothing, they show up in UI and they function.
I've tested this in build 0.2.7 on the PC, and on several Enslaved NPCs, and it works; it allows altering the urethral stats via clothing enchanted by the PC.
@Innoxia this is obviously just how I assume that the game should work from the rest of the available enchantments; if the current paradigm is intentional it'd be nice to know.

Clothing Enchantments alter Vaginal Urethra stats

---

src/com/lilithsthrone/game/Game.java
src/com/lilithsthrone/game/Properties.java
src/com/lilithsthrone/game/character/CharacterUtils.java
src/com/lilithsthrone/game/dialogue/utils/EnchantmentDialogue.java

This fixes bug #152 
changed all calls 
`StreamResult(File(String))` 
to 
`StreamResult(String)`
The solution might be the result of StreamResult corrupting Filepath by adding "file:%Filepath%" as pointed out here https://stackoverflow.com/questions/15324008/writing-xml-in-java-filenotfoundexception
tested with latest Version in Repo (v0.2.9.1)

fixed bug #152 (Hash Symbol in File Path prevents saving)

---

src/com/lilithsthrone/controller/MainControllerInitMethod.java
src/com/lilithsthrone/game/Properties.java
src/com/lilithsthrone/game/character/persona/SexualOrientation.java
src/com/lilithsthrone/game/character/persona/SexualOrientationPreference.java
src/com/lilithsthrone/game/character/race/RacialBody.java
src/com/lilithsthrone/game/dialogue/utils/OptionsDialogue.java

This change adds an option for players to set the encounter rates for the sexual orientation of random NPCs, in the same way as gender encounter rates.
The generation function uses both the generic player-defined rates and call-specific rates when computing the final orientation. The specific rates can be used for race/feminity-dependent rates. For example, harpies were previously hardcoded as being almost always gynephilic, and now use the generation function with unbalanced specific rates.
-----
- No new graphical assets are required.
- This change has been tested on version 0.2.6.5.
- I am Otter#4718 on discord.

Add configuration of NPCs sexual orientation encounter rates

---

src/com/lilithsthrone/game/inventory/clothing/AbstractClothingType.java

The path portion of imageEquippedName was left out. Also, don't
have two separate image entries if imageName and imageEquippedName
are the same.
As mentioned by Kobolds here: https://discordapp.com/channels/302617912949211136/446038411791433729/521647452139290624
Tested on version: 0.2.12.96
Discord handle: CognitiveMist|Phlarx

Fix for imageEquippedName

---

src/com/lilithsthrone/game/character/GameCharacter.java
src/com/lilithsthrone/main/Main.java

No longer given additional perk points on level up, instead relying on the getPerkPointsAtLevel function added in 0.3. This means that gameCharacters should no longer receive double perk points on level up.
Now saving perk point value using getAdditionalPerkPoints instead of getPerkPoints, as this saves the value that the load function is expecting. This means that the perk point value will no longer change on save/load (this was causing negative perk points, but it could also cause absurdly inflated perk points)
Tested with a fresh character on version 0.3:
Perk points were at the value expected for each level, and we unaffected by saving or loading.

Fix for perk point weirdness

---

src/com/lilithsthrone/controller/eventListeners/TooltipInformationEventListener.java
src/com/lilithsthrone/main/Main.java

Changelog for 0.3:
> Changed transformation references of 'breasts' and 'ass' to 'nipples'
> and 'anus', as that's all the transformation is affecting. (Breast
> and ass coverings are based on your torso's covering.)
Since 0.3 the body part types for ass and breast should actually
describe the appearance of the anus and nipples. The npc tooltip
about the body part types still revealed nipples and anus type even if
those areas are covered and unknown by the player.

Alter Tooltip to respect renamed coverable areas

---

res/txt/places/dominion/lilayasHome/lab.xml

Swaps a then and else that were reversed, Lilaya was reacting to the condom breaking when it was a scenario where you simply didn't wear one.

Fixes a Lilaya Condom Breaking reaction then/else error

---

src/com/lilithsthrone/game/character/effects/Perk.java

This commit fixes parsing for player job perks so that, theoretically, they can be used for NPCs and would display their descriptions correctly. This was done as a prelude to looking into doing NPC job perks.

UtilText parsing for player career/background perks

---

.gitignore

Adds .jar files to .gitignore so that they don't get repeatedly added to the GitHub tree, or updated, or all of that. Anti-frustration feature for people building the game on Eclipse to actually play it and to develop the game concurrently.
(No credit needed for this one.)

Add .jar files to .gitignore

---

src/com/lilithsthrone/game/character/effects/StatusEffect.java

Also, as discussed in issue #1046 :
Related fixes complete the separation of exposed chest status description  into exposed breasts and exposed nipples applying to feminine bodies.
No new graphical assets, leverages getCoverableAreaBreastsFlat() where appropriate.
Tested on 0.3.1

Issue 1046: Fix for potential divsion-by-zero error that breaks elements of the 0.3.1 GUI.

---

res/txt/places/dominion/harpyNests/alexa.xml

Replace Java syntax in XML text with the javax.script.ScriptEngine variable conventions established by game.dialogue.utils.UtilText.initScriptEngine().
This issue #1061  seen in at least 0.3.0.7 and 0.3.1
Tested in  0.3.0.7 (with res change) and 0.3.1 (complete build)

Issue 1061 Fix "(Error in conditional parsing!)" seen in Alexa's nest

---

src/com/lilithsthrone/game/dialogue/utils/OptionsDialogue.java

Provide less techno-jargon version of tooltip for Resume button for new installation prior to any save.
No new graphical assets. Fix for issue #1065 
Tested in 0.3.1

Issue 1065 For first time run, enhance tooltip on Resume button.

---

src/com/lilithsthrone/game/Properties.java

This fixes game-ending ConcurrentModificationException seen on 2 different JVMs on a MacBook Air at initial writing of data/properties.xml when Properties.setValue() was called by one thread while Properties.savePropertiesAsXML() was still iterating over Properties.values.
The key change is we loop over an enum possible values instead of the mutable HashSet.
I didn't see this issue #1067  in 0.3.0.7 official builds, but it broke my attempts to test my own builds of 0.3.1
No new graphical assets.
Tested in 0.3.1

Issue 1067 Fix ConcurrentModificationException while iterating over Properties.values

---

res/images/characters/modding.txt
src/com/lilithsthrone/controller/MainControllerInitMethod.java
src/com/lilithsthrone/controller/eventListeners/tooltips/TooltipInformationEventListener.java
src/com/lilithsthrone/rendering/Artwork.java
src/com/lilithsthrone/rendering/CachedGif.java
src/com/lilithsthrone/rendering/CachedImage.java
src/com/lilithsthrone/rendering/ImageCache.java

This is a relatively simple PR to allow adding animated GIFs as character images.
It is now possible to select .gif files when adding character images. Mostly due to performance considerations, they are loaded slightly differently than static images:
- Only the first frame is used for tooltips (prevents lag when hovering)
- Only the first frame is used if the file is larger than 10 MB (prevents huge files filling cache and memory); A warning is printed to the console
- The animation is not rescaled before caching (prevents long loading times as we'd have to rescale each frame separately and then reassemble the animation)
- Warnings have been added to the image readme and button description
All of these were implemented due to the simple fact that animations can have completely …

Animated GIF support

---

src/com/lilithsthrone/game/character/race/RacialBody.java
src/com/lilithsthrone/utils/Units.java

It was assumed that the size values in the game were in metric units while they were in fact in imperial units.
@Innoxia

Fixed the unit conversion

---

src/com/lilithsthrone/game/dialogue/utils/UtilText.java
src/com/lilithsthrone/rendering/RenderingEngine.java
src/com/lilithsthrone/utils/SvgUtil.java

The game's text parser recently got the ability to parse out comments,
denoted by //, but it was a bit overzealous. It would consume things that
shouldn't be comments, such as urls like http://lilithsthrone.blogspot.co.uk,
leaving just http: hanging, and obliterating everything else on that line.
This caused the start screen to look weird, and nearly every svg to be rendered
at the wrong size.
I've put in a fix for this by adding a negative lookbehind for ':'. Other
options could be to require comments are on their own line (not ideal),
comments begin with ' //' (that is a space, then two slashes), or similar,
but I think this is the least restrictive option.
This issue was introduced in commit f04832cb. Bad Inno, you should be
doing smaller commits more often, even if you don't push them …

Fix for over-eager comment removal and other rendering foibles

---

src/com/lilithsthrone/utils/Units.java

And another one. Honestly, at 5000 lines changed there were bound to be some inconveniences. But since it's all about convenience, those shall also be fixed.
- Fix missing sign of negative values
- Fix rounding issues (most notably for imperial sizes)
- Use plural for value 0
- Wrap long singular inches to \*-foot-\* (recommended to me as more readable than something like 80-inch, I have never used the imperial system so I wouldn't know)
All changes have been tested on 0.3.1.1.

Unit fixes

---

src/com/lilithsthrone/game/dialogue/npcDialogue/SlaveDialogue.java

Before these commits, consensuality in these scenes was being ignored/discarded after being calculated, always returning "false". These changes fix the scenes to properly take the calculations into account.

Fixes some flags in SlaveDialogue

---

src/com/lilithsthrone/game/Properties.java
src/com/lilithsthrone/game/character/npc/NPC.java

_This allows future in-client settings or pref file editing to adjust the randomization of npc forced-tf potions which I find tends toward same-race too often. Sometimes I want to spawn humans that prefer furry races in their tfs or want more surprise. Doesn't actually alter the probability. I would add an option to set the variable but not yet gotten around to figuring out the options menus._
Adds in configurable probability of the the racial body pref for NPCs being randomized (and therefor race of forced-tf potions). Saves/loads a float in the properties file as the percentage chance of a randomized race. Default still uses 15% random, 85% same-race.
New Properties config variable ( randomRacePercentage default 0.15f ), saving and loading in properties.xml, getter for variable ( …

Configurable chance for randomized body pref / forced-tf race

---

src/com/lilithsthrone/controller/MainControllerInitMethod.java
src/com/lilithsthrone/game/Game.java
src/com/lilithsthrone/game/PropertyValue.java
src/com/lilithsthrone/game/character/attributes/LustLevel.java
src/com/lilithsthrone/game/character/effects/StatusEffect.java
src/com/lilithsthrone/game/dialogue/encounters/Encounter.java
src/com/lilithsthrone/game/dialogue/encounters/EncounterType.java
src/com/lilithsthrone/game/dialogue/utils/OptionsDialogue.java

*This adds one of some proposed optional difficulty/scenario options.*
*This difficulty option will increase the probability of random encounters when the player is beat up or obviously easy prey. The increased probability is only applied to encounters that want to take advantage of the player. The encounter probability "boost" is determined by:*
- *energy level*
- *lust level*
- *dirty clothing/body*
- *exposed body parts*
- *"drunk" state*
*no*
*by me, with various versions from 3.0+* …

Add difficulty option: Opportunistic Attackers

---

res/clothing/innoxia/foot/heels.xml
src/com/lilithsthrone/controller/MainController.java
src/com/lilithsthrone/game/character/GameCharacter.java
src/com/lilithsthrone/game/character/npc/submission/ImpAttacker.java
src/com/lilithsthrone/game/combat/Spell.java
src/com/lilithsthrone/game/dialogue/npcDialogue/OccupantDialogue.java
src/com/lilithsthrone/game/dialogue/places/dominion/EnforcerHQDialogue.java
src/com/lilithsthrone/game/dialogue/places/dominion/lilayashome/RoomPlayer.java
src/com/lilithsthrone/game/dialogue/places/submission/GamblingDenDialogue.java
src/com/lilithsthrone/game/dialogue/places/submission/SlimeQueensLair.java
src/com/lilithsthrone/game/inventory/clothing/AbstractClothing.java
src/com/lilithsthrone/game/sex/Sex.java
src/com/lilithsthrone/game/sex/managers/SexManagerInterface.java
src/com/lilithsthrone/utils/Util.java

After noticing that loading a savefile could take up to 19 seconds, Bast and I checked with a profiler to find places with performance issues. The resulting fixes brought the loading times back down to 4 seconds. It probably also significantly affected game startup time.
- Fixes a typo in clothing file which means we don't have to run the string matcher in that case
- Fixes the string matcher to check for the best case first, which seems to apply in pretty much all cases after fixing the one typo I saw earlier.
That's one's a massive speed up.
I tried some other assorted attempts at speeding the game up, which may or may not really have worked. It at least seems sensible to not go printing how a character feels about their lust being loaded, but it's not something that you'd notice as …

Performance fixes for savefiles

---

src/com/lilithsthrone/game/inventory/CharacterInventory.java

This doesn't fix much, but it does fix the case where you'd be told that you can't unequip X as X is blocked by Y and X. It should now state you can't unequip X because it is blocked by Y.

Alter clothing blocked by message to not include the clothing which is blocked

---

src/com/lilithsthrone/game/dialogue/npcDialogue/OccupantDialogue.java

Fix issue #1153 
Return to the room after adding a occupant as party member, preventing access to options now unavailable.
Changed the nextDialogue from "OCCUPANT_START" to "Main.game.getDefaultDialogueNoEncounter()" after adding an occupant to the party.
~~**This change have not been tested yet, I haven't created the build environment yet.**~~
**Edit: Already tested, see [below](https://github.com/Innoxia/liliths-throne-public/pull/1154#issuecomment-491531990).**
If you want to test if this fixes the issue:
- Have an occupant able to join your party.
- Talk to it.
- Add it to the party.
- You shouldn't be able to keep talking in the occupant menu, as it's now disabled because "this character is currently working", effectively keeping you from initiating sex from the character's occupant …

Fix issue #1153

---

src/com/lilithsthrone/controller/MainControllerInitMethod.java
src/com/lilithsthrone/controller/eventListeners/TooltipInformationEventListener.java
src/com/lilithsthrone/game/Properties.java
src/com/lilithsthrone/game/character/GameCharacter.java
src/com/lilithsthrone/game/character/effects/Perk.java
src/com/lilithsthrone/game/character/effects/PerkManager.java
src/com/lilithsthrone/game/character/effects/StatusEffect.java
src/com/lilithsthrone/game/combat/Combat.java
src/com/lilithsthrone/game/combat/CombatMove.java
src/com/lilithsthrone/game/combat/CombatMoveType.java
src/com/lilithsthrone/game/combat/DamageType.java
src/com/lilithsthrone/game/combat/Spell.java
src/com/lilithsthrone/game/dialogue/utils/CombatMovesSetup.java
src/com/lilithsthrone/game/dialogue/utils/PhoneDialogue.java
src/com/lilithsthrone/res/moves/arcane-strike.svg
src/com/lilithsthrone/res/moves/avert.svg
src/com/lilithsthrone/res/moves/block.svg
src/com/lilithsthrone/res/moves/hoof-kick.svg
src/com/lilithsthrone/res/moves/strike.svg
src/com/lilithsthrone/res/moves/tease.svg
src/com/lilithsthrone/res/moves/twin-strike.svg
src/com/lilithsthrone/utils/Colour.java

Purpose:
* Implement the changes to combat outlined previously
Changes:
* Complete overhaul of combat loop
* Turn based system changed to AP based turn system
* Able to see intents of enemies in combat
* Abilities available to any character in combat are limited to maximum of 8 - respective menu added to phone to assign abilities
* Combat AI is a little smarter now, although improvements can be made
* As a result of the complete overhaul of the abilities, racial moves are not available in full yet.
* Spells are not balanced for this system  either.
* HP formula changed to avoid physique playing a major role in it. Might change the calculations again later, however.
* Mana formula changed to overally bring the amount of mana to 100-120 average values.
* A massive overhaul to unarmed …

Combat rework

---

src/com/lilithsthrone/game/character/npc/dominion/DominionSuccubusAttacker.java

Fix the display of error text in the incubus's main attack.
Filled out the target argument in UtilText.parse() DominionSuccubusAttacker
No
tested on latest dev - 3.3.6
TheKingInYellow

Fixed npc2 reference

---

src/com/lilithsthrone/game/inventory/enchanting/AbstractItemEffectType.java

- **What is the purpose of the pull request?**
If you have multiple horn types the enchantment UI randomized the selected horn type.
- **Give a brief description of what you changed or added.**
The param `int index` wasn't being used in that corresponding function. Instead the `HornType` was chosen randomly. Changed that to actually use the index of the choice.
- **Are any new graphical assets required?**
No
- **Has this change been tested? If so, mention the version number that the test was based on.**
Yes, 0.3.3.6 Alpha.
I haven't checked, if that breaks elsewhere aka, if the randomness was intended for 'other stuff', although I highly doubt that.
- **So we have a better idea of who you are, what is your Discord Handle?**
Stadler#3007

Fix unintentional randomness in horn enchanting

---

src/com/lilithsthrone/game/combat/Combat.java

During combat, if a character uses an ability that has an effect that targets multiple combatants, it will fail thus freezing the turn when you end it. This is due to the fact that multi-target effects call the `getRandomAlliedPartyMember(GameCharacter target)` method. This method returns a random ally from the target's party. The problem is if the target is alone, the function still tries to find a random ally from the empty list, and since `random.nextInt()` can't accept a 0 value, it fails.
Basically, I just checked if the list of targeted allies was equal to 0, and if so just return the target itself, instead of trying to find a random ally from an empty list.
- Are any new graphical …

Combat Multi-Target Effects Freeze/Crash Fix

---

src/com/lilithsthrone/game/character/GameCharacter.java

Fix a bug with health calculation that  was introduced in 7cb874c.
Added an additional check so the Aura penalty for having a low Arcane stat no longer also applies to Health.
No.
On the newest dev version(0.3.4).
Alaco on Discord.

fix health bug introduced in 03311

---

src/com/lilithsthrone/game/sex/positions/SexPositionOther.java

[5:30 PM] Pilcrow: trying to set up reverse-facesitting puts an error in the log instead;
Error: getContent() method is throwing an exception in the node: 'Positioning Selection: Lying down'
and accepting the position generates no 'new position' text.
Renamed variables in a conditional from `faceSitting` to `faceSittingReversal`. Error possibly caused due to copy/paste.
No
0.3.4.1 Alpha
Sphilia : @Reyvateil#5830

[FIX] Changing position to Face sitting reversal caused exception

---

src/com/lilithsthrone/world/places/PlaceUpgrade.java

Potential Typo / Copy Error
There was a reference to salve room double's list when defining slave room quadruple's list but that sort of cross reference is not seen elsewhere.
Discord tag GammaMike#6081

Potential copy error or typo in PlaceUpgrade.java

---

src/com/lilithsthrone/game/character/PlayerCharacter.java

Added null check into PlayerCharacter.getQuest.
Without this patch some dialogues (e.g. Clothing Emporium, Arcane Arts) in v0.3.5.4 fail with NullPointerException.

Fix some stores (e.g. Clothing Emporium) being broken

---

lilithsThroneBuildTutorial.md
pom.xml

This pull request replaces #1126 .
I have tried in vain to do the whole "rebasing" thing in git, but luckily Github offers this cheap workaround.
**- What is the purpose of the pull request?**
1. fixed mvn warnings about platform-dependent encoding; cp-1252 (Windows default) is probably not the best choice for... anything ever
2. eliminated one paragraph from "Tutorial for Building Liliths Throne" by adjusting output to be simply "as expected"
**- Give a brief description of what you changed or added.**
1. added default encoding to pom.xml
2. changed target path for res folder to be outside of classes
3. removed obsolete paragraph from lilithsThroneBuildTutorial.md
4. accidentally eliminated some trailing whitespaces from lilithsThroneBuildTutorial.md... but chose not to revert this …

Two minor Maven configuration adjustments

---

src/com/lilithsthrone/game/character/GameCharacter.java
src/com/lilithsthrone/game/dialogue/places/submission/LyssiethPalaceDialogue.java

Fixes #1247 
Added a wrapper around `getSubspeciesOverride().getRace()` named `getSubspeciesOverrideRace()` which returns `Race.NONE` as a fallback. I simply wanted a fix, that avoids `if (xyz() != null)`-checks. This should fix the NullPointerExceptions when visiting Lyssieth.
No
Tested in 0.3.5.8
Stadler#3007

Fixing NullPointerExceptions when visiting Lyssieth

---

src/com/lilithsthrone/game/dialogue/companions/OccupantDialogue.java

What is the purpose of the pull request?
Fix the minor issue with sex in an apartment being public when the occupant has just moved in
Give a brief description of what you changed or added.
Set the boolean IsApartment to true in the dialogue when the occupant moves to the apartment
Are any new graphical assets required?
No
Has this change been tested? If so, mention the version number that the test was based on.
Yes, version 0.3.5.8

Set apartment to true when occupant moves out

---

src/com/lilithsthrone/game/dialogue/utils/PhoneDialogue.java

What is the purpose of the pull request?
Fix the display of sex stats in the phone menu.
Give a brief description of what you changed or added.
The display of stats for blowjobs performed and received were reversed. (The creampie stats are OK).
Are any new graphical assets required?
No
Has this change been tested? If so, mention the version number that the test was based on.
Yes, version 0.3.5.8

Fix the phone menu sex stats display for blowjobs performed and received.

---

src/com/lilithsthrone/game/character/body/CoverableArea.java

Fix the issue where an NPC's oral skill can never be discovered
CoverableArea mouth has saveDiscoveredArea set to false. 
There is a check in setAreaKnownByCharacter to see if it is true, and since it never is, 
this blocks gaining knowledge of this area by the MC
To fix this, the value has been set to true.
No
Yes, version 0.3.5.8

CoverableArea mouth can never be discovered, blocking knowledge of NPC's oral skills

---

src/com/lilithsthrone/game/inventory/clothing/AbstractClothingType.java

When patterns are applied, it stomps on all existing definitions, including gradients.
Tested on my own build of the game, and also via manual inspection by dumping the svg strings to the console and looking at the differences in the results.

Fix using both patterns and gradients together

---

.gitignore
res/clothing/innoxia/torso/tshirt_test_item.xml
src/com/lilithsthrone/game/inventory/ColourReplacement.java
src/com/lilithsthrone/utils/colours/ColourListPresets.java

**- What is the purpose of the pull request?**
Expand the available dye selection on the debug shirt
Add NetBeans and Windows generated filetypes
**- Give a brief description of what you changed or added.**
Added 2 new entries to .gitignore
Added BaseColour and damage colors to a new color ArrayList, changed the starting ArrayList for dyes to this new list
Only the debug shirt should ever use this
**- Has this change been tested? If so, mention the version number that the test was based on.**
Tested on 0.3.9
**- So we have a better idea of who you are, what is your Discord Handle?**
dsg#4931

Expand dye selection on test shirt, additional ignored filetypes

---

src/com/lilithsthrone/game/combat/moves/CombatMove.java

Fix a bug where having multiple arm pairs allows an all-out strike with a 2-handed weapon
Check all arm pairs for 2-handed weapons. Only if at least one pair is not using 2-h weapons is an all-out strike allowed. Also check if the main weapon is 2-handed, if so, do not apply any damage in the off-hand attack.
No
Yes, tested in version 3.9.1 with various weapon combinations and arm pairs.
AceXp#0930

Check all arms for 2-h weapons

---

src/com/lilithsthrone/game/character/npc/dominion/DominionSuccubusAttacker.java
src/com/lilithsthrone/game/dialogue/npcDialogue/dominion/AlleywayDemonDialogue.java

Prevent any succubus alleyway attackers from spawning with the 'Prude' trait, as it doesn't fit them.
Remove the trait (if present, it's a very low chance anyway)
No
Yes, version 0.3.9.1
AceXp#0930

No prude succubus alleyway attackers

---

src/com/lilithsthrone/controller/MainControllerInitMethod.java
src/com/lilithsthrone/game/Game.java
src/com/lilithsthrone/game/Properties.java
src/com/lilithsthrone/game/PropertyValue.java
src/com/lilithsthrone/game/dialogue/responses/Response.java
src/com/lilithsthrone/game/dialogue/utils/OptionsDialogue.java
src/com/lilithsthrone/game/sex/sexActions/SexActionInterface.java

Add a new option for the bypass sex action content setting.
Remove the boolean value, and add a property. There are three possible values: None, Limited and Full:
None: There will be no options to bypass sex action corruption requirements, you are limited in your actions based on your corruption and fetishes. This is the same as the old OFF
Limited: Sex action corruption requirements may be bypassed if your corruption level is one level below the required corruption level of the action, but you will gain corruption if you do so.
Full: All sex action corruption requirements may be bypassed, but you will gain corruption if you do so. This is the same as the old ON.
- Are any new graphical …

Add new option for sex action bypass

---

src/com/lilithsthrone/game/dialogue/companions/OccupantDialogue.java

Fix issue #1356 'Moved Out; still getting lodging options'
Set the companionManagement (inventory and so on) to return to the OCCUPANT_APARTMENT dialogue if starting from an apartment. Also, when first visiting, set the npc as the managementCompanion so the dialogue recognizes the npc as present.
This is in the to_do list as 
"my daughters that have already moved out seem to be treated as though they haven't. All the dialogue options are reverted back as if they're still living with me. (Can ask what they think about my slaves, ask them to move out, etc.)" ca. line 496
No
- Has this change been tested? If so, mention the version number that the test …

Return to correct dialogue when leaving inventory management in an apartment

---

src/com/lilithsthrone/game/inventory/item/AbstractItemType.java
src/com/lilithsthrone/game/sex/Sex.java

While carrying an arcane makeup set, characters will reapply heavy lipstick whenever it wears off.
Works for the player and for npc's.
As a part of this change, added an overload to `AbstractItemType.getName` and `AbstractItemType.getNamePlural` that allows specifying whether the result should be capitalized.

Reapply Heavy Makeup

---

src/com/lilithsthrone/game/character/GameCharacter.java

Fix a parser error in the vagina reveal description
-- Switched the parser targets (revealer and revealed) to make it compatible with the penis reveal description
-- Do the parsing at the end, rather than in each seperate case
-- And thereby fix the bug in the (Fetish.FETISH_VAGINAL_GIVING).isNegative()) part
No
Yes, tested in 0.3.9.5
AceXp#0930

Fix a parser error in the vagina reveal description

---

src/com/lilithsthrone/rendering/Pattern.java

Enable loading patterns from the res/mods/[author]/items/pattern folder.
Determine if there are xml files in any res/mods/[author]/items/pattern folders, and try to load them (and the corresponding svg file). And then add this as a pattern.
No
Yes, tested in 0.3.9.7 by putting all the polka dot files in a local res/mods folder
AceXp#0930

Enable loading patterns from res/mods folder

---

src/com/lilithsthrone/game/dialogue/places/dominion/RedLightDistrict.java

Not a large pull request, but I can include these things.
Fixes a balance/continuity issue when acting as a submissive partner in the Angel's Kiss
Dialogue states that the client enters "Around twenty-five minutes later", but the ANGELS_KISS_SELL_SELF_SUB DialogueNode only progresses time by 5 minutes. This has been fixed to make the node take 25 minutes instead.
No.
Only so far as to ensure that the fix works, on version 0.3.9.7

Fixed time bug in Angel's Kiss Sub scene

---

src/com/lilithsthrone/game/dialogue/places/dominion/slaverAlley/SlaverAlleyDialogue.java

Fixes an issue where Accepting Sean's challenge in the Slaver's alley wouldn't initiate a fight scene
In commit 3ec95aa, the NPC's base clothing was changed without changing the fight scene preparation, wherein Sean removes some equipment, including a tie that no longer exists. This lead to a NullPointerException in `GameCharacter.unequipClothingIntoInventory`, which prevented the scene from moving any further into the fight sequence.  
This PR changes the fight scene preparation.
No.
Tested in 0.3.9.7, only so far as to ensure that the fix works
- So we have …

Fixed Sean's fight scene

---

src/com/lilithsthrone/game/character/GameCharacter.java
src/com/lilithsthrone/game/dialogue/utils/InventoryDialogue.java

Fix issue #1317 Wrong text when reading a book in defeated enemy's inventory
I have defeated a leopard in battle and read his book "Curious kitties". The game said: "The leopard produces a book, titled 'Curious Kitties', which he then forces you to read…".
Since it is the player issuing the command to use an item, the text should involve the player. However, the default useItem will use an item from the inventory of the character involved, so this also had to be changed. The text wil be based on the player, but the item will be removed from the NPC inventory (if it is consumable).
No
- Has this change been tested? If so, mention the version number …

Change how items in an NPC inventory are used

---

src/com/lilithsthrone/game/dialogue/utils/UtilText.java

Fix the bug where characters get lost when parsing speech, leading to parserTarget.Character() not found! errors.
Save the current list of characters for parsing, and restore it when the parsing is done, so that calling parse recursively works properly
No
Yes, tested with 3.9.9.9
AceXP#0930

Save character list for each call when parsing

---

src/com/lilithsthrone/game/dialogue/utils/UtilText.java

Fix glow commands
- bare `glow` was missing
- `glowFreedom` wasn't rainbow'd (and other rainbow-ables, too)
Tested on 0.3.9.9, no new assets required.

Fix glow commands

---

src/com/lilithsthrone/game/character/PlayerCharacter.java

The player's description always shows the default description ("Having been pulled into an enchanted mirror..."), even if changed with save editing. This change makes it use the default description if there's no custom description.
Tested with 3 new characters, 1 character with custom description, and 1 pre-existing character, on 0.3.9.8.

Player Selfie uses custom description if available

---

src/com/lilithsthrone/game/dialogue/places/dominion/slaverAlley/ScarlettsShop.java
src/com/lilithsthrone/game/dialogue/story/CharacterCreation.java
src/com/lilithsthrone/game/dialogue/utils/BodyChanging.java
src/com/lilithsthrone/game/dialogue/utils/CharacterModificationUtils.java

Add the option for a slave to be mute to Helena's custom slave shop.
fix #1349
Added a boolean to allow specials in getPersonalityChoiceDiv. Currently only Mute is a special.
Also removed the option to change tongue colour in the Hair options tab (probably a copy/paste error).
No
Yes, tested in 3.9.9.9. Slaves can now be mute, the main character cannot be mute.
AceXP#0930
After merging this PR issue #1349 Customise Slave can be closed.

Add option for mute slaves in custom slave shop

---

src/com/lilithsthrone/game/sex/Sex.java

Characters with the NON_CON_DOM fetish will gain lust when having sex with someone that is resisting.
fix #1347
Add a positive lust gain in this situation. 
No
Yes, tested with version 3.9.9.9 (with the save file attached to issue #1347 Non-consent bug)
AceXP#0930
After this PR is merged, issue #1347 Non-consent bug can be closed.

Increase lust when the partner of a noncon fetishist is resisting

---

res/txt/encounters/dominion/generic.xml
res/txt/places/dominion/slaverAlley/genericDialogue.xml
res/txt/places/submission/gamblingDen/pregnancyRoulette.xml
src/com/lilithsthrone/game/character/CharacterUtils.java
src/com/lilithsthrone/game/character/npc/dominion/Cultist.java
src/com/lilithsthrone/game/character/npc/dominion/Elle.java
src/com/lilithsthrone/game/character/npc/dominion/Kate.java
src/com/lilithsthrone/game/character/npc/dominion/Lilaya.java
src/com/lilithsthrone/game/character/npc/dominion/Ralph.java
src/com/lilithsthrone/game/character/npc/submission/Roxy.java
src/com/lilithsthrone/game/inventory/enchanting/ItemEffectType.java
src/com/lilithsthrone/game/inventory/item/AbstractItem.java
src/com/lilithsthrone/game/inventory/item/ItemType.java

Special NPC's (like Lilaya and Kate) should treat brood mother pills much the same as other fertility pills.
Added a isTypeOneOf method to AbstractItem, and use this when determining if a special reaction is needed.
Also, Roxy now sells brood mother pills, and there is a chance random NPC's will have them as well.
And several scenes still mention the Breeder pills as pink, but they have been purple for some time. Those occurances have been changed.
No
Yes, tested with 3.9.9
AceXP#0930

Added check for fertility pills, including broodmother

---

src/com/lilithsthrone/controller/eventListeners/InventorySelectedItemEventListener.java

Fix the bug where clicking on an equipped item while enchanting during a trading session gives you full access to the inventory of the trader, allowing to take all their equipped items and the items in their inventory.
The InventorySelectedItemEventListener will do nothing when you are in the ENCHANTMENT_MENU. I.e. when you now click an equipped item while enchanting, nothing will happen.
Since you can never enchant equipped items, this action is not needed anyway.
No
Yes, tested with 3.9.9
- So we have a better idea of who you are, what is your Discord …

Disallow access to equipped items while enchanting

---

src/com/lilithsthrone/controller/MainControllerInitMethod.java
src/com/lilithsthrone/game/dialogue/utils/EnchantmentDialogue.java
src/com/lilithsthrone/game/inventory/enchanting/LoadedEnchantment.java

Make it possible to apply recipes (stored enchantment lists) to weapons that already have an enchantment
Choose a weapon with no enchantment to apply the recipe to, and if none are available choose the first one that has (one or more) enchantments. In all cases, the weapon must be the same type as the one the recipe was made for.
Also, when loading a recipe, add the effects on the item that is to be enchanted to the list of effects in the enchantment dialogue, and not just the list of effects that were in the recipe.
No
Yes, tested with 3.9.9
- So we have a …

Enchantment recipes can now be applied to weapons that already have enchantments

---

src/com/lilithsthrone/game/character/race/Subspecies.java

Fix a bug where having an elemental in a feral form leaves the left and right sidebar blank
Check if the feral subspecies of the elemental has it's SVGstrings initialised before accessing them
No
Yes, tested with version 3.11
AceXP#0930

fix bug with passive form of elementals

---

src/com/lilithsthrone/game/character/body/abstractTypes/AbstractPenisType.java
src/com/lilithsthrone/game/character/body/abstractTypes/AbstractVaginaType.java
src/com/lilithsthrone/game/inventory/enchanting/AbstractItemEffectType.java

Multiple vagina and penis types weren't handled correctly in `vagina.xml` and `penis.xml` files and only the first vagina and penis type was handled in enchanting.
`<transformationName>` wasn't parsed for vags 'n cocks and TF_TYPE_1 was hardcoded there. Fixed that.
No.
Yes, 0.3.13 Alpha
`@Stadler#3007`

Allow multiple vagina and penis types per race

---

src/com/lilithsthrone/controller/MainController.java
src/com/lilithsthrone/res/css/webViewTooltip_stylesheet.css
src/com/lilithsthrone/res/css/webViewTooltip_stylesheet_light.css

Tooltip fade-in animation is now toggleable via the existing 'Fade-In' game option.
Addresses #1444:
When using Java 8u271, there is a bug with animations in JavaFX WebView (https://bugs.openjdk.java.net/browse/JDK-8256138). In LT, this causes tooltips to appear blank for users with that version of Java.
This change addresses that bug by restricting tooltip animation to the game's 'Fade-In' option, which is disabled by default. Without the animation, tooltips render normally.
No new graphical assets required. Tested on 0.3.9.9.

Tooltip animation is toggleable

---

src/com/lilithsthrone/game/character/race/AbstractSubspecies.java
src/com/lilithsthrone/game/dialogue/utils/UtilText.java

Improve performance by storing the result of getSubspeciesWeighting
Load race descriptions from characters/raceInfo if there is no bookEntries file (like the new Cougar subspecies)
Store the result of getSubspeciesWeighting and use this for the comparison and to assign it as a value
Only load from the bookEntries file if it exists, otherwise use the characters/raceInfo for parsing.
No
Yes, tested with 0.3.14
AceXP#0930

store result of getSubspeciesWeighting to improve performance

---

src/com/lilithsthrone/controller/eventListeners/tooltips/TooltipInformationEventListener.java

Change to account for less/more than two antenna per row.
Change tooltip for antenna to reflect exact number of antenna
Change how tooltip for antenna counts from `2 * rows` to `number per row * rows`
No
Yes, 0.3.14 alpha
deboucher#8190

Change antennae counting for tooltip
